### ISSUE TITLE
Error while dialing dial unix /etc/kubernetes/secrets-store-csi-providers/azure.sock

### ISSUE THREAD

**Issue by sambhavdtu** [kubernetes-sigs/secrets-store-csi-driver#1003]
**What steps did you take and what happened:**
I see the following errors in logs of csi-secrets-store pod

`E0718 20:45:10.185935       1 nodeserver.go:235] "failed to mount secrets store object content" err="rpc error: code = Canceled desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial unix /etc/kubernetes/secrets-store-csi-providers/azure.sock: connect: no such file or directory\"" pod="default/geneva-services-645lv"`
`E0718 20:45:10.185970       1 nodeserver.go:235] "failed to mount secrets store object content" err="rpc error: code = Canceled desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial unix /etc/kubernetes/secrets-store-csi-providers/azure.sock: connect: no such file or directory\"" pod="default/geneva-services-645lv"`
`I0718 20:45:10.185987       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1f43f7c5-6ebe-4877-8fd4-bbe07df83c6c/volumes/kubernetes.io~csi/mdsd-secret-volume/mount" pod="default/geneva-services-645lv"`

**Anything else you would like to add:**
1. I am using the version of v1.2.0 of csi-secrets-store and v1.2.0 of csi-secrets-store-provider
2. These are the configuration of provider-volume and additional-provider-volume-paths
      `--provider-volume=/var/run/secrets-store-csi-providers`
     `--additional-provider-volume-paths=/etc/kubernetes/secrets-store-csi-providers`

providers-dir:
    Type:          HostPath (bare host directory volume)    
    Path:          /etc/kubernetes/secrets-store-csi-providers  
    HostPathType:  DirectoryOrCreate 
providers-dir-0:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/secrets-store-csi-providers 
   HostPathType:  DirectoryOrCreate

-------------------------
Volumes:
  providervol:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/secrets-store-csi-providers
    HostPathType:  

3. My doubt here is why the csi-driver is trying to connect to this socket /etc/kubernetes/secrets-store-csi-providers/azure.sock , it should ideally try to connect to socket /var/run/secrets-store-csi-providers/azure.sock

**Which provider are you using:**
Azure Key Vault

**Comment by nilekhc** [comment]
Hello @sambhavdtu, Were you trying to upgrade from some previous version? Could you share yaml output for both driver and provider pods?

**Comment by sambhavdtu** [comment]
Hi Nilekh, 

These are few points I would like to add based on some investigation I did today.
1. I have updated the socket path where CSI provider listens to connections from clients from /etc/kubernetes/secrets-store-csi-providers to /var/run/secrets-store-csi-providers.
2. I have added provider-volume and additional-provider-volume-path in CSI driver daemon set yaml



"--provider-volume=/var/run/secrets-store-csi-providers"
"--additional-provider-volume-paths=/etc/kubernetes/secrets-store-csi-providers"



3. Now the issue is that, CSI driver pod gets updated first when the old provider pod is running on the node, it connects to the old provider pod on the socket path '/etc/kubernetes/secrets-store-csi-providers/azure.sock'
   . When the new CSI provider pod comes up, it no longer listens on the old socket path '/etc/kubernetes/secrets-store-csi-providers/azure.sock'



But, the CSI driver keeps on trying to connect on the old path only. These are the error logs -



I0719 14:26:18.891102       1 nodeserver.go:352] "Using gRPC client" provider="azure" pod="tier2-57c645b4-8bj8l"
I0719 14:26:18.891264       1 nodeserver.go:352] "Using gRPC client" provider="azure" pod="tier2-57c645b4-8bj8l"
E0719 14:28:18.887808       1 nodeserver.go:235] "failed to mount secrets store object content" err="rpc error: code = Canceled desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial unix /etc/kubernetes/secrets-store-csi-providers/azure.sock: connect: no such file or directory\"" pod="default/tier2-57c645b4-8bj8l"
I0719 14:28:18.887868       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/f18a15c7-b30a-4654-bd83-086a4a0e34b4/volumes/kubernetes.io~csi/mdm-secret-volume/mount" pod="default/tier2-57c645b4-8bj8l"




4. On going through csi-driver code I saw that we cache the socket path.
5. I am guessing this is a bug on CSI driver side, because if it fails to connect on the old cached socket path, it should once again try all the socket paths in provider-volume and
additional-provider-volume because the CSI driver might get stuck permanently trying the old socket path and volume mount will never succeed.

**Comment by nilekhc** [comment]
@sambhavdtu Correct. Driver initializes the provider client at the start and maintain that connection. We are retiring `/etc` path and probably deprecate `--additional-provider-paths` in future. For now I would recommend restarting driver pod.

**Comment by sambhavdtu** [comment]
Hi @nilekhc , Thanks. Restarting the driver pod indeed mitigates the issue. But, there seem to be no safe way for upgrading the provider volume path currently. There are always chances of breaking live clusters. 
Can we expect any solution or safe practice for this ?

**Comment by aramase** [comment]
> Hi @nilekhc , Thanks. Restarting the driver pod indeed mitigates the issue. But, there seem to be no safe way for upgrading the provider volume path currently. There are always chances of breaking live clusters.
Can we expect any solution or safe practice for this ?

@sambhavdtu As Nilekh mentioned, this change is a backward compatible way to move from using `/etc/` to `/var/run` for the provider sockets. Instead of forcing it in a single release, we're allowing providers to make the changes and be ready for the move. In the next release or the release after, we will completely remove `/etc` from the driver which means if the provider is still using old paths, it would fail. The safe practice here is to deploy the driver and then the latest provider (as directed by each provider) to use the new paths. For Azure Provider, the recommendation would be use the latest release that uses `/var/run` for sockets. If you're installing the Azure provider and driver using helm charts from the provider repo, you shouldn't have any issues with the upgrade because they're packaged based on the compatibility.

**Comment by sambhavdtu** [comment]
Thanks @aramase.
