### ISSUE TITLE
Pod with CSI volume does not mount when using Azure RBAC permission model on Azure Key Vault

### ISSUE THREAD

**Issue by dewolfs** [kubernetes-sigs/secrets-store-csi-driver#1008]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When I deploy the secretProviderClass and deployment below in combination with an Azure Key Vault permission model "**Vault access policy**", everything works fine.  The user-assigned identity of the AKS cluster is assigned All Secret permissions on the Key Vault resource level.

When I deploy the secretProviderClass and deployment below in combination with an Azure Key Vault permission model "**Azure role-based access control**", I get the error as seen below under Events.

I've tried assigning the roles Key Vault Administrator, Key Vault Secrets Office and Key vault Secrets User on the Key Vault resource level (inheritance to secrets) and also on the individual secrets level.

**SecretProviderClass.yml**
> apiVersion: secrets-store.csi.x-k8s.io/v1
> kind: SecretProviderClass
> metadata:
>   name: azure-kv-aks-csi-011-system-msi-01
>   namespace: default
> spec:
>   provider: azure
>   parameters:
>     usePodIdentity: "false"
>     useVMManagedIdentity: "true"    # Set to true for using managed identity
>     userAssignedIdentityID: "98033b94-b23a-4e50-8f17-bdea609c41e9"      # If empty, then defaults to use the system assigned identity on the VM
>     keyvaultName: "kv-aks-csi-011"
>     cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
>     objects:  |
>       array:
>         - |
>           objectName: db-user
>           objectType: secret        # object types: secret, key or cert
>           objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
>         - |
>           objectName: db-pass
>           objectType: secret        # object types: secret, key or cert
>           objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
>     tenantId: "f0d1d268-e79f-49c2-b61c-5ec11119b78c"                 # the tenant ID of the KeyVault
> 

**Deployment.yml**
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: nginx-deployment
>   namespace: default
>   labels:
>     app: nginx
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: nginx
>   template:
>     metadata:
>       labels:
>         app: nginx
>     spec:
>       containers:
>       - name: nginx
>         image: nginx:1.23.1
>         ports:
>         - containerPort: 80
>         resources:
>           requests:
>             memory: "64Mi"
>             cpu: "250m"
>           limits:
>             memory: "128Mi"
>             cpu: "500m"
>         volumeMounts:
>         - name: secrets-mount
>           mountPath: "/mnt/secrets-store"
>           readOnly: true
>       volumes:
>         - name: secrets-mount
>           csi:
>             driver: secrets-store.csi.k8s.io
>             readOnly: true
>             volumeAttributes:
>               secretProviderClass: "azure-kv-aks-csi-011-system-msi-01"

**Events**
> Events:
>   Type     Reason       Age               From               Message
>   ----     ------       ----              ----               -------
>   Normal   Scheduled    23s               default-scheduler  Successfully assigned default/nginx-deployment-c46fc5c96-9nkbd to aks-nodepool1-31443732-vmss000000
>   Warning  FailedMount  7s (x6 over 23s)  kubelet            MountVolume.SetUp failed for volume "secrets-mount" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-deployment-c46fc5c96-9nkbd, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:db-user, objectVersion:: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=98033b94-b23a-4e50-8f17-bdea609c41e9;oid=80de5f9e-a8a7-4672-b3ce-b19439584f37;iss=https://sts.windows.net/f0d1d268-........../\r\nAction: 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/......../resourcegroups/rg-prd-001/providers/microsoft.keyvault/vaults/kv-aks-csi-011/secrets/db-user'\r\nAssignment: (not found)\r\nVault: kv-aks-csi-011;location=germanywestcentral\r\n" InnerError={"code":"ForbiddenByRbac"}

**What did you expect to happen:**

- CSI driver works with the both Azure key vault permission models.  Adopting least privilege principle allows us with the RBAC permission model to fine-grained provide access to an individual secret.
- CSI volume gets mounted and secrets are available inside the pod

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I've waited more than 10 mins to propagate the permissions as indicated here : https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#known-limits-and-performance

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

- Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.1.0
- Kubernetes version: (use `kubectl version`): v1.22.11

**Comment by aramase** [comment]
Hello 👋🏻  Thanks for reporting the issue. As this issue is specific to Azure Key Vault provider, I would recommend opening an issue [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues).

I'll close this one and let you open an issue there for further questions. Please feel free to reopen if you have any questions about the driver. 

/close
