### ISSUE TITLE
cannot sync secret with ca.crt from vault csi driver

### ISSUE THREAD

**Issue by srinath-panda** [kubernetes-sigs/secrets-store-csi-driver#1009]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
CA.crt, tls.key and tls.crt are stored in vault as KV. 
When trying to use vault CSI driver to sync it as a kubernetes.io/tls secret, ca.crt could not  synced to cluster
Getting ` err: key 'ca.crt' is not supported. Only 'tls.key' and 'tls.crt' are supported]` 
**What did you expect to happen:**

Create kubernetes secret of type kubernetes.io/tls with ca.crt, tls.key and tls.crt fields populated. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
HashiCorp Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag) hashicorp/vault-csi-provider:1.1.0
- 
- Kubernetes version: (use `kubectl version`): 1.21

**Comment by froblesmartin** [comment]
Same here.

In my case, I need to load the `ca.crt` in the secret to be able to use ingress Nginx [Client Certificate Authentication](https://kubernetes.github.io/ingress-nginx/examples/auth/client-certs/).

**Comment by kgalic** [comment]
Hello, 

I loaded the cacert in the secret, and I also get the same problem. Any ideas why does this fail, how can I load in the k8s secert cacert besides my tls.crt and the tls.key? 

Thanks in advance!

**Comment by srinath-panda** [comment]
For all ppl how I made it work is not to create a secret of type tls, but a generic secret.
