### ISSUE TITLE
More verbose documentation with examples for enabling syncSecret feature 

### ISSUE THREAD

**Issue by abhishek181** [kubernetes-sigs/secrets-store-csi-driver#1055]
**Describe the solution you'd like**
By default the syncSecret feature is disabled. I understand that option information is provided in the below documentations:
 - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/221ef44211750661b2407e608ff707517d7a940a/charts/secrets-store-csi-driver/values.yaml#L187-L188
 - https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#values

However, providing the same information in the README file the Github repo would be more helpful. There could be a table with all the options that can be added when installing the csi-driver and some examples to enable some of them.

**Anything else you would like to add:**
Examples with setting the optional values using flags will help as well where a simple command can help to enable the feature.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest image installed using helm
- Kubernetes version: 1.22

**Comment by aramase** [comment]
> However, providing the same information in the README file the Github repo would be more helpful. There could be a table with all the options that can be added when installing the csi-driver and some examples to enable some of them.

@abhishek181 The optional values table is available in the docs - https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#optional-values

**Comment by aramase** [comment]
Closing with https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1055#issuecomment-1253997763.

Please feel free to reopen if you have any other issues.

/close
