### ISSUE TITLE
Updation of K8s secrets

### ISSUE THREAD

**Issue by rajashekhargundeti** [kubernetes-sigs/secrets-store-csi-driver#1056]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Application is deployed with one pod and one SPC with two secrets to be fetched from a vault. Secrets are mounted onto pod volume. K8s secret is created with two data elements. 
Next, the SPC is updated to fetch one additional secret(in both parameters and secretObjects sections), and application is scaled to two pods.
Pod-1 has a mount with 2 secrets.
Pod-2 has a mount with 3 secrets.

What should we expect in the k8s secret, two secrets or three secrets? 
Note: This is tested with auto rotation flag disabled.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
OCI and mounting is delegated to the driver.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.2.0
- Kubernetes version: (use `kubectl version`): 1.24.1

**Comment by aramase** [comment]
@rajashekhargundeti This is already documented here: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#mounted-content-and-kubernetes-secret-not-updated. If you're not using auto rotation, you'll need to delete the Kubernetes secret for it receive the updated secrets in `SecretProviderClass`.

**Comment by aramase** [comment]
Closing this with https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1056#issuecomment-1262691380.

Please feel free to reopen if you have more questions.

/close
