### ISSUE TITLE
Emit `level` field in structured (json) logging

### ISSUE THREAD

**Issue by jcogilvie** [kubernetes-sigs/secrets-store-csi-driver#1073]
**Describe the solution you'd like**
Structured (i.e. json) logging should emit a `level` field (or equivalent) for use in indexing/parsing.  Right now, the logs seem to emit the `v` field but no `level`, leaving it hard to distinguish what's an info vs. an error log in json.

Slack discussion indicates that potentially using something like `vmware-tanzu/pinniped` `plog` could help.  

**Anything else you would like to add:**
I am using datadog as a log storage/search platform.  

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  v1.2.4
- Kubernetes version: (use `kubectl version`):  1.22

**Comment by nilekhc** [comment]
Ref: https://kubernetes.slack.com/archives/C013PUP2WRK/p1664505589573909

**Comment by enj** [comment]
I have exported `vmware-tanzu/pinniped.plog` into a standalone package at [monis.app/mlog](https://monis.app/mlog) so that it can be easily used here.  See #1134
