### ISSUE TITLE
Change behaviour of 404 SecretNotFound to avoid failures

### ISSUE THREAD

**Issue by joshwright10** [kubernetes-sigs/secrets-store-csi-driver#1082]
**Describe the solution you'd like**
I am using Key Vault Secrets to store `AppSettings.json` data, and use CSI to retrieve the configuration data from the Azure Vault, which then maps to Env variables in the Deployment.  
I now have a setting in AppSettings.json, which is currently null, but may be configured later. As I can't seem to add a null value into Key Vault, I cannot create the KV secret. However, I would like the config in place in Kubernetes for the day when this needs a value, without the need to re-deploy to Kubernetes.

At the moment, if the secret is missing from Key Vault, but defined in `SecretProviderClass`, the pod fails with the errors below.  
It would be nice to allow secrets to be optional, and not cause a failure if missing from the Key Vault.

> Unable to attach or mount volumes: unmounted volumes=[secrets-store01-inline], unattached volumes=[kube-api-access-jqz5g secrets-store01-inline]: timed out waiting for the condition

> MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod example/test-service-58b68d4f77-t22nm, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:kvsm-AppConfig-Example, objectVersion:: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SecretNotFound" Message="A secret with (name/id) kvsm-AppConfig-Example was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182"

**Anything else you would like to add:**
No

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.2.2.3
- Kubernetes version: (use `kubectl version`): Client Version: v1.25.2, Kustomize Version: v4.5.7, Server Version: v1.23.8

**Comment by aramase** [comment]
> It would be nice to allow secrets to be optional, and not cause a failure if missing from the Key Vault.

@joshwright10 Even if the secret is optional, that essentially results in 1 API call to the external secrets store to determine if it exists and also it will not be a deterministic behavior. Please feel free to add your thoughts [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/645) as this needs to be supported at the provider level.

Closing this issue as it's a provider feature request.

/close
