### ISSUE TITLE
Resource requests and limits for helm CRD hooks

### ISSUE THREAD

**Issue by haugom** [kubernetes-sigs/secrets-store-csi-driver#1083]
**Specify resource requests and limits for crd hooks in helm chart**

I would like to be able to specify resource limits and requests for the jobs that are created in the helm hooks for upgrade and keep crd jobs.

When a person uses the helm chart to install the secrets-store-csi-driver, the jobs (keep-crd and upgrade-crd) that are created does not specify any requests for the pods.

In a namespace with LimitRange defined (https://kubernetes.io/docs/concepts/policy/limit-range/) the pods will easily get oomkilled.

**Comment by aramase** [comment]
@haugom would you be interested in opening a PR to update the helm charts in [manifest_staging/charts](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/manifest_staging/charts/secrets-store-csi-driver) dir?

**Comment by haugom** [comment]
Hi

Yes. I will be happy to help.
