### ISSUE TITLE
Secret provider takes the Disabled secret value from KV

### ISSUE THREAD

**Issue by aliaksei-babuk** [kubernetes-sigs/secrets-store-csi-driver#1087]
**What steps did you take and what happened:**
For adding auto rotation we have added the next configuration row in to helm configuration:
  parameters:    
    enableSecretRotation: "true"

**What did you expect to happen:**
We expect that the fresh one secret value will be automatically added to the secret 

**Anything else you would like to add:**
We have test secret in Azure KeyVault. With next values:
test1 Disaibled
test2 Disaibled
test3 Disaibled
test4 Enabled
test5 Enabled - Latest

When I have added a change to the config, CSI starts randomly taking test4 and test3 values after secret manual deletion.
**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1
- Kubernetes version: (use `kubectl version`): 1.24.4

**Comment by aramase** [comment]
The values fetched from secrets store (Azure Key Vault) are done by the provider and the driver has no control over this. I'll close this issue as it's not a driver issue. Please open an issue in the provider repo.

/close
