### ISSUE TITLE
Bug: annotations inserted into DaemonSet labels

### ISSUE THREAD

**Issue by JRemitz** [kubernetes-sigs/secrets-store-csi-driver#1093]
@nilekhc - It appears that with #1043 a series of labels were added.  The `labels` block appears to be incorrectly injected into the `annotations` block. 

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/b3fef62ee10a71e70884d6d904dbd6f9bee0d1cb/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml#L22

**Comment by nilekhc** [comment]
@JRemitz Thanks for reporting this. Could you please share an example?

**Comment by nilekhc** [comment]
Ah, see it now. It should be like following:

![image](https://user-images.githubusercontent.com/1626598/200074230-892b3a33-6fe2-4848-9177-8ad0b9f9f999.png)


It's an easy fix. Would you like to open a PR?

**Comment by lakshkeswani** [comment]
@nilekhc I am interested in working on this issue, It will be great if assign this to me.
