### ISSUE TITLE
Document load test results

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#111]
Figure out where the system fails at scale and attempt to address these issues

- [ ] Have load test results documented
 - Size of cluster
 - SKU
 - Number of secret provider class and pods

Use the data above for recommended resource limits

**Comment by ritazh** [comment]
We can get baseline [measurements](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2#measurement) using clusterloader2.

**Comment by aramase** [comment]
/assign @aramase 

Plan to setup a testgrid job that runs load tests with kind against each PR.
