### ISSUE TITLE
Volume mount fails on windows node

### ISSUE THREAD

**Issue by ayuzzz** [kubernetes-sigs/secrets-store-csi-driver#1128]
Hi team, we are facing an issue w.r.t secret-store csi driver on a windows node which is behind a proxy server. We want to know if there is some firewall configuration (or some other configuration) that is needed specifically for such machines.

We are getting the following error message for the application which uses the driver :
```
MountVolume.SetUp failed for volume "secrets-store02-inline" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  3m1s (x475 over 23h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[secrets-store02-inline], unattached volumes=[secrets-store02-inline kube-api-access-whlvf]: timed out waiting for the condition
```

We also see the following error on secret-store pod logs for container "secret-store" :

```
{"ts":1671613958670.3242,"caller":"secrets-store/nodeserver.go:242","msg":"failed to mount secrets store object content","pod":{"name":"win-secretmanagement-6f947656d6-v9k62","namespace":"testapp"},"err":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"ts":1671613958670.3242,"caller":"secrets-store/nodeserver.go:88","msg":"unmounting target path as node publish volume failed","v":0,"targetPath":"c:\\var\\lib\\kubelet\\pods\\0bf9ba4d-5362-44c3-9f00-a9ff51d5a859\\volumes\\kubernetes.io~csi\\secrets-store02-inline\\mount","pod":{"name":"win-secretmanagement-6f947656d6-v9k62","namespace":"testapp"}}
{"ts":1671614080702.347,"caller":"secrets-store/nodeserver.go:359","msg":"Using gRPC client","v":0,"provider":"azure","pod":"win-secretmanagement-6f947656d6-v9k62"}
```

**These are some details regarding our setup :**

Kubernetes distribution : RKE2
We are using azure arc and the azuresecretprovider extension
We are using the following application (the placeholders get properly replaced by our kustomization file) :
[secretprovider.zip](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/10276481/secretprovider.zip)
The following solution works on a host machine which is not behind a proxy
Windows node is 2019 data server

**Comment by aramase** [comment]
@ayuzzz Thank you for opening the issue.

This issue is specific to the arc-extension of the Azure Key Vault provider for Secrets Store CSI Driver. Could you open an issue there? Thanks!

/close
