### ISSUE TITLE
Failed Mount - volume mode "Ephemeral" not supported by driver secrets-store.csi.k8s.io (no CSIDriver object)

### ISSUE THREAD

**Issue by tanayk2311** [kubernetes-sigs/secrets-store-csi-driver#1135]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I have installed the CSI Driver and Azure Key Vault Provider using this doc - https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer.yaml and 
https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/v1.3.0/deploy.

I have added following volume in the pod deployment yaml file.
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "hcep-akv-class"
          nodePublishSecretRef:
            name: akv-secrets-store-creds

SecretProviderClass and the application pod are in same namespace.

But still I am getting this error in the pod when I execute this command : kubectl describe po
Failed Mount - volume mode "Ephemeral" not supported by driver secrets-store.csi.k8s.io (no CSIDriver object)

Logs of the 3 containers of Secret Store CSI Driver which is one the same node as application pod.

**kubectl logs -f hcep-csi-secrets-store-df5pl -n kube-system -c node-driver-registrar**
I0113 09:38:40.827633       1 main.go:166] Version: v2.6.2
I0113 09:38:40.827714       1 main.go:167] Running node-driver-registrar in mode=registration
I0113 09:38:40.828469       1 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0113 09:38:40.828515       1 connection.go:154] Connecting to unix:///csi/csi.sock
I0113 09:38:44.767649       1 main.go:198] Calling CSI driver to discover driver name
I0113 09:38:44.767679       1 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginInfo
I0113 09:38:44.767686       1 connection.go:184] GRPC request: {}
I0113 09:38:44.826067       1 connection.go:186] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v1.3.0"}
I0113 09:38:44.826159       1 connection.go:187] GRPC error: <nil>
I0113 09:38:44.826173       1 main.go:208] CSI driver name: "secrets-store.csi.k8s.io"
I0113 09:38:44.826222       1 node_register.go:53] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0113 09:38:44.826458       1 node_register.go:62] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0113 09:38:44.826579       1 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I0113 09:38:45.244125       1 main.go:102] Received GetInfo call: &InfoRequest{}
I0113 09:38:45.244457       1 main.go:109] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/csi-secrets-store/registration"
I0113 09:38:45.296657       1 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}

//////////////////////////////////////////////////////////////////////////////////////

**kubectl logs -f hcep-csi-secrets-store-df5pl -n kube-system -c secrets-store**
I0113 09:38:44.228022       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I0113 09:38:44.230866       1 main.go:182] starting manager
I0113 09:38:44.333907       1 secrets-store.go:46] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.3.0" buildTime="2022-12-13-20:41"
I0113 09:38:44.334259       1 reconciler.go:130] "starting rotation reconciler" rotationPollInterval="2m0s"
I0113 09:38:44.341625       1 server.go:121] "Listening for connections" address="//csi/csi.sock"
I0113 09:38:45.245606       1 nodeserver.go:365] node: getting default node info

////////////////////////////////////////////////////////////////////////////////////////////////

**kubectl logs -f hcep-csi-secrets-store-df5pl -n kube-system -c liveness-probe**
I0113 09:38:47.129490       1 main.go:149] calling CSI driver to discover driver name
I0113 09:38:47.130869       1 main.go:155] CSI driver name: "secrets-store.csi.k8s.io"
I0113 09:38:47.130900       1 main.go:183] ServeMux listening at "0.0.0.0:9808"

///////////////////////////////////////////////////////////////////////////////////////////////

Logs of the Azure Keyvault Provider which is one the same node as application pod.

**kubectl logs -f hcep-csi-secrets-store-provider-azure-l4qdr -n kube-system**
I0113 09:38:44.937878       1 main.go:76] "Starting Azure Key Vault Provider" version="v1.4.0"
I0113 09:38:44.937956       1 exporter.go:14] "intializing metrics backend" backend="prometheus"
I0113 09:38:44.937991       1 main.go:96] construct pem chain feature enabled
I0113 09:38:44.938374       1 main.go:138] "Listening for connections" address="//provider/azure.

//////////////////////////////////////////////////////////////////////////////////////////

**Highlighted is the CSIDriver:**
<img width="825" alt="image" src="https://user-images.githubusercontent.com/122606057/212300496-c3b6a030-5a41-446e-9903-6a3185833f40.png">

////////////////////////////////////////////////////////////////////////////
**kubectl get events --field-selector involvedObject.name=<<application pod >>**
LAST SEEN   TYPE      REASON        OBJECT                                MESSAGE
33m         Normal    Scheduled     pod/osgp-ui-starter-dcc9897bf-trbfs   Successfully assigned hcep-dev-ns/osgp-ui-starter-dcc9897bf-trbfs to aks-agentpool-30936446-vmss00000b
3m3s        Warning   FailedMount   pod/osgp-ui-starter-dcc9897bf-trbfs   **MountVolume.NewMounter initialization failed for volume "secrets-store" : volume mode "Ephemeral" not supported by driver secrets-store.csi.k8s.io (no CSIDriver object)**
11m         Warning   FailedMount   pod/osgp-ui-starter-dcc9897bf-trbfs   Unable to attach or mount volumes: unmounted volumes=[secrets-store], unattached volumes=[secrets-store kube-api-access-l8ttt]: timed out waiting for the condition
15m         Warning   FailedMount   pod/osgp-ui-starter-dcc9897bf-trbfs   Unable to attach or mount volumes: unmounted volumes=[secrets-store], unattached volumes=[kube-api-access-l8ttt secrets-store]: timed out waiting for the condition

**What did you expect to happen:**
The volume should be mounted on the pod and kubernetes secret should be created in the kubernetes cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
Azure Key Vault provider is being used.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): registry.k8s.io/csi-secrets-store/driver:v1.3.0
- Kubernetes version: (use `kubectl version`): 1.23.8

**Comment by aramase** [comment]
@tanayk2311 The driver name you have in the volume definition must match the driver name installed. In the screenshot you shared, you have reconfigured the driver name to `hcep-secrets-store.csi.k8s.io` but in the volume you're referring to `secrets-store.csi.k8s.io`.  If you want to change the driver name, you also need to configure it in the command line flag `--driver-name`: https://secrets-store-csi-driver.sigs.k8s.io/topics/command-reference.html.

**Comment by aramase** [comment]
Closing this issue with https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1135#issuecomment-1382182246. Please feel free to reopen if you have any other questions.

/close
