### ISSUE TITLE
Auto Rotation of secrets with Azure Key Vault Provider doesn't happen even though it is enabled

### ISSUE THREAD

**Issue by joovieira123** [kubernetes-sigs/secrets-store-csi-driver#1136]
What steps did you take and what happened:
I installed the CSI driver and the Azure Key Vault Provider for Secrets Store with helm and enabled auto rotation with a sync period of 2 mins.
Everything works well except for the autorotation of the secrets. When I update a secret in the keyvault to a new value, thus a new version, this new version does not get propagated in the cluster anywhere (not in the mounted volume, not in the k8s secret). Of course that if I redeploy the pod then it shows up, but as for my understanding of this feature that's what the auto rotation should do right? or am I not understanding the proper function of this?

Bellow is a screen shot of a new and an old version of a test secret in the keyvault. When describe the SecretProviderClassPodStatus I can clearly see that the secret hasn't been updated to the new version. Also if I exec into the pod and cat the secret from the volume mount I also see it's value is still the one from the old version.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/69449052/212361087-22b60edd-7466-4a59-b98c-2a031af0bae5.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/69449052/212361379-561d9d17-6516-4173-8555-56c8deb86803.png">

What did you expect to happen:
Expected both the k8s secret and the secret that is in the volume mounted in the pod to be updated to the new version within the rotation reconciliation period that was established in the helm values.

Anything else you would like to add:
Also, when I checked the logs for the csi driver, it looks like the driver is reconciling, but it does it every 5 mins instead of every 2 mins like I requested through helm. Even though that when I describe the driver pod I can see that the rotation reconciliation period is set for 2 mins as I requested.
Bellow are the logs that I was able to collect both from the driver as the provider pods. Also the helm values being used in the config so you can see the difference between what I declare (2 min rotation) and what is really happening (5 mins rotation according to the timestamps of the logs). I am using FluxCD for a GitOps approach, that's why my helm values are in a yaml file.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/69449052/212362721-c5048ca9-bcb0-4ee4-aaba-017fdecb32a9.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/69449052/212362854-bd6157ad-d3a6-4cf4-9a9b-20836e2bdb4e.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/69449052/212363722-fce2a68e-a05e-42db-82ff-ed6e830ab41f.png">

<img width="833" alt="image" src="https://user-images.githubusercontent.com/69449052/212363966-f6385a31-e90b-4a44-84ef-d537df92eab1.png">

Which provider are you using:
Azure Key Vault Provider is being used.

Environment:
Secrets Store CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.0
Azure Key Vault Provider version: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.0
Kubernetes version: client --> 1.23.4, server --> 1.24.3

**Comment by aramase** [comment]
> Bellow are the logs that I was able to collect both from the driver as the provider pods. Also the helm values being used in the config so you can see the difference between what I declare (2 min rotation) and what is really happening (5 mins rotation according to the timestamps of the logs). I am using FluxCD for a GitOps approach, that's why my helm values are in a yaml file.

@joovieira123 I don't think the helm installation was done with the correct values. If secret rotation was enabled during install, you'll see `--enable-secret-rotation=true` and `--rotation-poll-interval=2m` args in the driver. In the screenshot you shared, those flags are missing. I would recommend checking your install steps to ensure the correct values are being passed on.

**Comment by joovieira123** [comment]
Super many thanks for the quick response @aramase! I will re-install everything from scratch and report here if it worked...

**Comment by joovieira123** [comment]
@aramase thank you so much for your help... after proper re-installation of the driver the secret auto rotation works like a charm :)
