### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#115]

**Comment by aramase** [comment]
#164 adds windows support for drivers
https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/28 will add windows support for azure provider
  - pod identity mode will not be supported

Will close this issue when official windows driver and provider images are available

**Comment by aramase** [comment]
Windows support has been added for the driver and azure provider. 

Pending: doc update with instructions for windows.
