### ISSUE TITLE
Listing a provider for OCI( Oracle Cloud Infrastructure)

### ISSUE THREAD

**Issue by rajashekhargundeti** [kubernetes-sigs/secrets-store-csi-driver#1151]
Hi,

We are planning to publish secrets store csi driver provider for OCI Vault, and would like to get it listed in the Supported providers section (https://secrets-store-csi-driver.sigs.k8s.io/#supported-providers).

Could you please let us know the process.

Thanks,
Rajashekhar

**Comment by aramase** [comment]
Hello 👋🏻 

Here are the details for adding a provider to the supported providers: https://secrets-store-csi-driver.sigs.k8s.io/providers.html. Feel free to reach out on [slack](https://github.com/kubernetes-sigs/secrets-store-csi-driver#want-to-help) if you have any questions.

**Comment by aramase** [comment]
@rajashekhargundeti Do you still plan on adding the OCI provider to the supported provider list?

**Comment by balkrishna93** [comment]
@aramase , yes we want to add the OCI provider to the supported provider list.

**Comment by aramase** [comment]
@balkrishna93 PTAL at https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1151#issuecomment-1402331663.
