### ISSUE TITLE
failed validation for secret object in spc default/podinfo, err: data is empty

### ISSUE THREAD

**Issue by amarpc** [kubernetes-sigs/secrets-store-csi-driver#1163]
**What steps did you take and what happened:**
 we installed the secret-store csi-driver using helm release and created service accounts & secret-provider-class for micro-services. through secret-provider-class we are trying to mount secrets from AWS secret manager to application pods on a specific path. So when we deploy application, once pod in running state it should populate secrets of that particular service in that service pod. But in our case, its populating the secrets. Pod also in running state, but getting this error pop-up "failed validation for secret object in spc default/podinfo, err: data is empty"

**What did you expect to happen:**
 when a service has secret-store csi-driver and service account & secret-provider-class.it should mount secrets into pod on specified path without any issue.

**Anything else you would like to add:**
 we are achieving the required thing. but still pod throwing the issue which I mentioned in title. Mainly this is happening for the services which are deployed newly. Same approach we are using for all other services some of them are working fine without having any issue, newly deployed services having the abovementioned issue. 

**Which provider are you using:**
    AWS secret manager

**Environment:**
  Development 
- Secrets Store CSI Driver version: (use the image tag):v1.3.0
- Kubernetes version: (use `kubectl version`): 1.22

**Comment by nilekhc** [comment]
@amarpc Thanks for opening the issue. Looks like this is AWS provider specific. Could you open an issue here - https://github.com/aws/secrets-store-csi-driver-provider-aws/issues

/close
