### ISSUE TITLE
Configurable Prometheus metrics boundaries

### ISSUE THREAD

**Issue by praveenjindal62** [kubernetes-sigs/secrets-store-csi-driver#1170]
**Describe the solution you'd like**
I would like to have an option to configure prometheus histogram metrics boundaries. Possible [here ](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/190069de55db4936ee9b7f88ae2eff965e7df510/pkg/metrics/prometheus_exporter.go#:~:text=DefaultHistogramBoundaries%3A%20%5B%5Dfloat64,%7D)?

**Comment by aramase** [comment]
> I would like to have an option to configure prometheus histogram metrics boundaries. Possible [here ](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/190069de55db4936ee9b7f88ae2eff965e7df510/pkg/metrics/prometheus_exporter.go#:~:text=DefaultHistogramBoundaries%3A%20%5B%5Dfloat64,%7D)?

could you provide an example of the histogram metrics boundaries you would like to configure instead of the defaults?
