### ISSUE TITLE
Mounting secret as env var only doesn't work

### ISSUE THREAD

**Issue by saedx1** [kubernetes-sigs/secrets-store-csi-driver#1176]
**What steps did you take and what happened:**
If I reference a secret as an env var **only** , it doesn't get created on/pre pod creation. However, if I add to that a volume and a volumeMount, then the secret gets created.

**What did you expect to happen:**
I would expect to be able to use it as a secret without having to mount it as a volume I'm not going to use.

**Anything else you would like to add:**
If this is expected to happen, is there a way around it? If you think more work is needed to have that and you feel it might be valuable, I'm ready to do the work for it and have a PR.

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
AWS. I did check them as well.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.3.1
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-ffeb93d", GitCommit:"f76e2b475d1433cdb6bd546e9e8f129fde938fb7", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by salaxander** [comment]
@saedx1 - that is expected behavior. As it is, you can't sync secrets to K8s secrets and use them without the empty volume mount because of the way the project interacts with the container storage interface. I'd suggest taking a look at[ External Secrets Operator](https://external-secrets.io/v0.8.1/) for that pattern
