### ISSUE TITLE
change `backOffLimit` in pre-upgrade hook jobs to allow retries

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#1205]
- Update the `backOffLimit` to allow retries on transient failures. The default value is 6 (xref: https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy). We might want to set to a lower value as new jobs are created with an exponential back-off delay. 

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/d681fc3c39bb2168a6547b89d90d86bd31c1852e/manifest_staging/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml#L91

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/d681fc3c39bb2168a6547b89d90d86bd31c1852e/manifest_staging/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml#L91

**Comment by Suraiya-Hameed** [comment]
I will pick this!
