### ISSUE TITLE
Vault secret store driver vs secret-store-csi-driver-azure

### ISSUE THREAD

**Issue by monicabiswal147** [kubernetes-sigs/secrets-store-csi-driver#1260]
I have a requirement to integrate the vault hosted externally with the kubernetes pods running in AKS. My AKS cluster already has the secret store driver provisioned by azure and is not allowing me to install the helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system
Can I use the azure provided secret store driver and proceed to create a serviceproviderclass or shall I install secrets-store-csi-driver/secrets-store-csi-driver with a different driver name?
Reason being the secretproviderclass yaml has provider as azure and I am not sure if it will work if I don't set the provider as vault

**Comment by aramase** [comment]
> My AKS cluster already has the secret store driver provisioned by azure and is not allowing me to install the helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system

You only need a single instance of the driver running in the cluster, so either use the AKS add-on or install the driver using helm charts.

> Can I use the azure provided secret store driver and proceed to create a serviceproviderclass or shall I install secrets-store-csi-driver/secrets-store-csi-driver with a different driver name?

If you need to use the driver with other providers than azure, I would recommend installing the driver directly and the individual providers you need to use. Only a single instance of the driver needs to be running and you can install multiple providers in the cluster simultaneously. 

/close
