### ISSUE TITLE
Debug driver image does not exsist

### ISSUE THREAD

**Issue by vajeen** [kubernetes-sigs/secrets-store-csi-driver#1265]
**What steps did you take and what happened:**
I followed the README.md to install the debug driver for setting up the csi driver, but debug-driver pod never started.

Error message
```
Warning   Failed              pod/debug-driver-66c9f98cd7-fr6nm                Failed to pull image "debug-driver:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/debug-driver:latest": failed to resolve reference "docker.io/library/debug-driver:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**What did you expect to happen:**
debug-driver po in running state

**Anything else you would like to add:**

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
AWS

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
You need to build the debug driver and load it in the kind cluster. The steps are in https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/.local/README.md#creating-a-docker-image.

/close
