### ISSUE TITLE
Update driver name to k8s.io

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#129]
Once the repo is moved under kubernetes-sigs org, then we can move from `secrets-store.csi.k8s.com` to the "k8s.io" domain.

**Comment by craiglpeters** [comment]
Shouldn't the title of this issue be "Update driver name to x-k8s.io"?

**Comment by ritazh** [comment]
no, one is the api “x-k8s.io” and one is the csi driver name “k8s.io”. They are two different things.
