### ISSUE TITLE
PodSecurityPolicy are deprecated in v1.21+ and not available in v1.25+

### ISSUE THREAD

**Issue by abdolence** [kubernetes-sigs/secrets-store-csi-driver#1298]
I see `PodSecurityPolicy` resources in this project still don't have any kind of replacement/support for v1.25+.
Details: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125

Are there any plans to support this transition?

**Environment:** Kubernetes v1.25+

- Secrets Store CSI Driver version: (use the image tag): <= 1.3.4
- Kubernetes version: (use `kubectl version`): 1.25

Thanks for great project and work!

**Comment by sozercan** [comment]
@abdolence I believe this is already done. 

PSP is only used in the helm chart if cluster supports it
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/templates/podsecuritypolicy.yaml#L1

**Comment by abdolence** [comment]
@sozercan I know you can disable them, but it is not clear what is the replacement for v1.25+. If we still need some configuration for Pod Security Admissions? It is possible we're just missing docs about it, but I'd great to just clarify what is the (recommended) migration path with PSP for CSI driver.
