### ISSUE TITLE
Add more ut for NodePublishVolume and NodeUnPublishVolume

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#132]
- [ ] increase test coverage for bad requests
- [ ] increase test coverage to check for diff returned error types
- [ ] increase test coverage to check for IsLikelyNotMountPoint

**Comment by irbekrm** [comment]
Hi! 
 I would like to work on this if it is still needed?
I see that there are already unit tests for most error scenarios for `NodePublishVolume` (although they don't test returned error types as in the description of this issue), but I could add tests for `NodeUnpublishVolume` and potentially also for `NodeStageVolume` and `NodeUnstageVolume`?

**Comment by aramase** [comment]
@irbekrm Thank you for picking this up. We would like to increase the unit test coverage across all packages. The driver only uses `NodePublishVolume` and `NodeUnPublishVolume`. So if we can increase the coverage for those methods, it'll be great. Please feel free to reach out if you have any questions.
