### ISSUE TITLE
k8s secret is not deleted/updated when ADO secret is updated

### ISSUE THREAD

**Issue by ShuiRuTian** [kubernetes-sigs/secrets-store-csi-driver#1327]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Create config, so that I got an environment variable from k8s secret, which is got from ADO key-vault secret. I also got a mounted content with a Kubernetes secret during this way.
2. enable secret rolling, and I do not change the default value, so it's 2m.
3. update key-vault secret in ADO and wait for some minutes.
4. restart the only one pod(or change the deployment app number to 0, and change it to 1 after some time).
5. The k8s secret is not updated, and the environment is not updated. However, the mounted content is updated.

**What did you expect to happen:**
The k8s secret should be updated and the environment variable should be updated.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have read 
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/book/src/topics/sync-as-kubernetes-secret.md
- https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#sync-mounted-content-with-a-kubernetes-secret
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/book/src/topics/secret-auto-rotation.md

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
Part from the config:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloud-test-api-auth
spec:
  provider: azure
```

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
Sorry, how should I got the image tag?
I found something through `kubectl get pods --all-namespaces -o jsonpath="{..image}"`
mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4
mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1

- Kubernetes version: (use `kubectl version`):
Server: v1.24.9

**Comment by porwalameet** [comment]
Did you try setting this config during deployment: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/enable-auto-rotation-secrets/

Auto-rotation of secrets, we have been using it and the k8s secrets are updated when a secret is updated in AKV.

**Comment by strowk** [comment]
Having the same issue now. We have "--enable-secret-rotation=true" passed to the driver, however our pods do not live for 120 seconds (they are short running jobs). Would that interfere with the rotation feature?
