### ISSUE TITLE
Empty .crt and .key files are generated for PFX format

### ISSUE THREAD

**Issue by JasonXD-CS** [kubernetes-sigs/secrets-store-csi-driver#1328]
**What steps did you take and what happened:**
```
        - |
          objectName: pfx-certificate
          objectType: secret
          objectFormat: pfx
```

When trying to download a certificate in `pfx` format like above, it downloads three files 
`pfx-certificate`, `pfx-certificate.crt` and `pfx-certificate.key`  
where the .crt and .key files are empty dummy files.

**What did you expect to happen:**
PFX format should only generate single certificate file.

**Anything else you would like to add:**

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):   
  - mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4
  - mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.8.0
- Kubernetes version: (use `kubectl version`):  v1.25.6

**Comment by aramase** [comment]
This is a provider specific change and not related to driver. I've opened https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1277 in AKV provider.

/close
