### ISSUE TITLE
solution of .env file 

### ISSUE THREAD

**Issue by Sakshione** [kubernetes-sigs/secrets-store-csi-driver#1365]
where should I do the set up my .env file??? in git repo,,,in future also it will not get any expose issue,,,give solution pls,,,I am deploying my code in AWS server

**Comment by aramase** [comment]
The description doesn't provide a lot of information. I'm not sure if this question is related to the Secrets Store CSI Driver. Please provide more details on the steps and what you're trying to.

/close
