### ISSUE TITLE
When trying to deploy multiple instances of SecretProviderClass to the same Namespace only one gets deployed and the Pod Deployment Fails

### ISSUE THREAD

**Issue by ic-mgriehm** [kubernetes-sigs/secrets-store-csi-driver#1449]
**What steps did you take and what happened:**
When trying to deploy multiple instances of SecretProviderClass to the same Namespace only one gets deployed and the Pod Deployment Fails

**What did you expect to happen:**
Both SecretProviderClasses get created, mounted to Pod, and the Pod can pull in Secrets from Each KeyVault as Environment variables in the Pod.

**Anything else you would like to add:**
The Pod tries to deploy but a Failure Event is reported that one of the SecretProviderClasses cannot be found and when we use kubectl to list the SecretProviderClasses in the Namespace only one appears, and normally it is the second one listed in the Kubernetes Manifest.

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 
  - mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.8.0
  - mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4-1
  -  mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.10.0
- Kubernetes version: (use `kubectl version`):  1.28.3

**Comment by ic-mgriehm** [comment]
@aramase 2 instances with different names in the same namespace.

**Comment by aramase** [comment]
> When trying to deploy multiple instances of SecretProviderClass to the same Namespace only one gets deployed and the Pod Deployment Fails

The issue description doesn't provider clear information about the error. Please provide example manifests and repro steps.

**Comment by aramase** [comment]
/close

Closing this issue due to insufficient information. Feel free to reopen with https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1449#issuecomment-1989680148.
