### ISSUE TITLE
When enableSecretRotation is set to true, the CSI driver requests a new dynamic database secret every time it polls vault

### ISSUE THREAD

**Issue by MonolithicMonk** [kubernetes-sigs/secrets-store-csi-driver#1453]
**What steps did you take and what happened:**
A new postgresql  database dynamic credential is generated and pods restarted (due to Stakater reloader) whenever the CSI driver polls vault for a change due to the enableSecretRotation key set to true.
This issue is limited to postgresql database dynamic secrets only.

**What did you expect to happen:**
What I expect to happen is that when the CSI driver polls vault for a dynamic credentials change, it should see that the previous lease is still valid and do nothing.

**What actually happens**
CSI driver acqually performs a read operation to acquire a new dynamic secret or somehow triggers the generation of new credentials

**Which provider are you using:**
HashiCorp Vault, I have checked for help

**Environment:**
Ubuntu 20.04

- Secrets Store CSI Driver version: v1.3.3
- Kubernetes version: v1.28.7

**Comment by MonolithicMonk** [comment]
I misunderstood how the secretRotation and syncing works.  My initial thought was that the feature simply checks if the secret within vault has changed, then updates the pod's secret with the new vault secret.  I now understand it to mean that it performs actual secrets generation / rotation on behalf of vault.

For those people using dynamic database credentials, this feature can yield unintended results.  For example, if you've already configured
your vault database dynamic credentials with a ttl, this feature can prematurely generate new credentials before the ttl has expired.

**Comment by aramase** [comment]
> I misunderstood how the secretRotation and syncing works. My initial thought was that the feature simply checks if the secret within vault has changed, then updates the pod's secret with the new vault secret. I now understand it to mean that it performs actual secrets generation / rotation on behalf of vault.

This is not correct. The CSI driver doesn't talk directly to the external secrets store (in this case vault). The driver simply makes a request to the provider asking for a list of secrets that need to be written to the filesystem. The provider is the one that gets the secret from external secrets store/generates it.

If you're having issues with the vault provider, I would recommend opening an issue [here](https://github.com/hashicorp/vault-csi-provider).

/close
