### ISSUE TITLE
CVEs on base image

### ISSUE THREAD

**Issue by dnlopes** [kubernetes-sigs/secrets-store-csi-driver#1456]
Hello team,

I just ran Trivy against the latest version and it's reporting 10 vulnerabilities:

<img width="1223" alt="imagem" src="https://github.com/kubernetes-sigs/secrets-store-csi-driver/assets/3472594/9d1d84b4-cf50-481e-8097-72b53e69322d">

Used the following CLI:

`trivy image --exit-code 1 --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL registry.k8s.io/csi-secrets-store/driver:v1.4.1`

Do you have plans to bump the dependencies to address these vulnerabilities? [According to the documentation](https://secrets-store-csi-driver.sigs.k8s.io/release-management#security-vulnerabilities), releases should come out every month, but it seems it has not been the case in the last months.

Thanks.

**Comment by aramase** [comment]
The next patch release is planned for early next week.

**Comment by dnlopes** [comment]
Awesome, good to know that. What about the cadence of patches? Is the documentation outdated? Or it's a matter of lack of capacity of the maintainers of this project? Or something else?

Thanks.

**Comment by xrsanet** [comment]
Thanks for the information, does next weeks release include bumping up minor releases of node-driver-registrar from 2.8.0 to v2.9.3 and livenessprobe from v2.10.0 to v2.11.0? As these contain vulnerabilities as well.

If this is being considered already, that is amazing, if not, I do not mind doing a PR tomorrow to include it, if that would help.

**Comment by aramase** [comment]
> Awesome, good to know that. What about the cadence of patches? Is the documentation outdated? It's a matter of lack of capacity of the maintainers of the project? Or something else? Are you looking for hands on maintaining the project?

The document is up-to date. The maintainers have just been busy with the Kubernetes v1.30 release work, but we'll be releasing every month to patch CVEs as mentioned in the doc. We're happy to have new contributors and if you interested in contributing in any ways to the project, feel free to ping me on the Kubernetes slack.

> That is great news that a patch release is being done next week, does this include bumping up minor versions of node-driver-registrar from 2.8.0 to v2.9.3 and livenessprobe from v2.10.0 to v2.11.0? As these are reporting vulnerabilities as well.

Yes, this will be included in the helm chart patch release next week.

**Comment by aramase** [comment]
Thanks for the patience. https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.4.2 has been released.

Closing this issue now. As per cadence, the next release will be next month.

/close
