### ISSUE TITLE
How to Update Security Context in Helm Chart

### ISSUE THREAD

**Issue by devopserio** [kubernetes-sigs/secrets-store-csi-driver#1477]
Hello,

I am trying to deploy the `secrets-store-csi-driver` Helm Chart in a Kubernetes cluster with restricted PodSecurityAdmission (PSA). I need to adjust the security context of the pods deployed by this Helm release to meet the requirements of the restricted PSA.

However, I couldn't find a way in the provided `values.yaml` to adjust the `securityContext` for the pods. Could you provide guidance or an example of how to set the `securityContext` to meet the following requirements:

- `securityContext.runAsNonRoot: true`
- `securityContext.allowPrivilegeEscalation: false`
- `securityContext.capabilities.drop: ["ALL"]`
- `securityContext.seccompProfile.type: "RuntimeDefault"`

Any help would be greatly appreciated.

Thank you.

**Comment by aramase** [comment]
Duplicate of https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1437.

https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1438 is currently under review. Please feel free to take a look at the PR and add comments.

/close
