### ISSUE TITLE
Helm chart repository

### ISSUE THREAD

**Issue by kinzleb** [kubernetes-sigs/secrets-store-csi-driver#154]
Could we use this github repo as a helm chart repository (similar to https://github.com/Azure/aad-pod-identity/tree/master/charts) and package a version of the chart?

The index.yaml and *.tgz could be kept here:  https://github.com/deislabs/secrets-store-csi-driver/tree/master/charts

I'm using the Terraform helm provider which requires a chart repository in order to work.

**Comment by burtlo** [comment]
As I'm writing some content to teach people how to use this with Vault, I would also appreciate the ability to install this via Helm targeting a released version.

```shell
$ helm install csi-secrets-store https://github.com/kubernetes-sigs/secrets-store-csi-driver/archive/v0.1.0.tar.gz
```

**Comment by jmcshane** [comment]
Could use this as well, also in Azure. Trying to use the CSI driver with AAD Pod Identity

**Comment by syedhassaanahmed** [comment]
+1
