### ISSUE TITLE
Orphan secret on SecretProviderClass deletion

### ISSUE THREAD

**Issue by RobinFrcd** [kubernetes-sigs/secrets-store-csi-driver#1584]
**What steps did you take and what happened:**
1. Create a `SecretProviderClass`
2. Wait for the `secret` to be created
3. Replace the `SecretProviderClass` with a new one
4. New secret is created, but old one is not delete

**What did you expect to happen:**
Old secret should be deleted

**Anything else you would like to add:**
My first issue was that a change in the `SecretProviderClass` didn't update the related secret. In my helm chart I implemented this solution: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/389#issuecomment-909516744 (add a `{{ .Release.Revision }}` suffix at the end of `SecretProviderClass`/`secretName`). So it creates a new secret at every release but doesn't delete the previous one, so I end up with **orphan secrets**.

**Which provider are you using:**
[AWS Secret Manager](https://github.com/aws/secrets-store-csi-driver-provider-aws)

**Comment by daniel-cohen** [comment]
I'm seeing the same issue .
I am adding a hash to the secret provider class name (and the secret it generates).
Argocd deletes the previous version  of the SecretProviderClass (annotated with `argocd.argoproj.io/sync-options: PruneLast=true`).

It seems the driver is failing to find the SecretProvideClass (deleted by argo) and just doesn't clean up:
logs:
```
csi.x-k8s.io \"properties-0fd4355607f90262580f\" not found"
secrets-store-csi-driver-xxx secrets-store E0515 01:24:51.158283       1 secretproviderclasspodstatus_controller.go:99] "failed to patch secret owner ref" err="failed to get spc properties-0fd4355607f90262580f, err: SecretProviderClass.secrets-store.csi.x-k8s.io \"properties-0fd4355607f90262580f\" not found"
secrets-store-csi-driver-xxx secrets-store I0515 01:24:54.057773       1 nodeserver.go:306] "node unpublish volume complete" targetPath="/var/lib/kubelet/pods/1259a1cd-2ded-4eb3-8413-6737f457e870/volumes/kubernetes.io~csi/properties-0fd4355607f90262580f/mount" time="2.259346ms"
```

Maybe I'm missing something here , but I don't see any code to delete a secret here, even in the latest version: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/9783f7e5469c7749937a54d221f7dc8bfb20bb87/controllers/secretproviderclasspodstatus_controller.go#L336



/remove-lifecycle stale
