### ISSUE TITLE
Csi-driver not creating k8s secrets

### ISSUE THREAD

**Issue by srreddy2020** [kubernetes-sigs/secrets-store-csi-driver#1611]
I have deployed below Helm Charts as daemonSets in K8s Cluster.
1)secrets-store-csi-driver-1.4.4
2)secrets-store-csi-driver-provider-aws-0.3.9

Instead of Mounting the secrets into Pod, i would like to have k8s native  secrets to get secrets from Aws Secrets Manager
When we deploy StorageProviderClass its not creating Secrets.
Pod stuck with **Error: secret "mysecret-k8s" not found**

IAM Role working fine and storageproviderClass Yaml also looks fine, as its working fine when i add Volume\volumeMounts to the POD,i am getting secrets from AWS.

**Which provider are you using:**
AWS Secrets Manager

**Environment:**
- Secrets Store CSI Driver version: v1.4.4
- Kubernetes version: v1.27

YAML file below..
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: csi-provider
  name: mysecret
spec:
  provider: aws
  secretObjects:
    - secretName: mysecret-k8s
      type: Opaque
      data:
      - objectName: "dataminds_svcs_database_dbpassword"
        key: "dataminds_svcs_database_dbpassword"
      - objectName: "dataminds_svcs_idm_password"
        key: "dataminds_svcs_idm_password"
  parameters:
    objects: |
      - objectName: "ci/apiplt/test"
        objectType: "secretsmanager"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: csi-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx1
  template:
    metadata:
      annotations:
        secrets-store.csi.k8s.io/used: "true"
      labels:
        run: nginx1
    spec:
      containers:
      - image: nginx:stable-alpine
        name: nginx1
        env:
          - name: dataminds_svcs_database_dbpassword
            valueFrom:
              secretKeyRef:
                name: mysecret-k8s
                key: dataminds_svcs_database_dbpassword
          - name: dataminds_svcs_idm_password
            valueFrom:
              secretKeyRef:
                name: mysecret-k8s
                key: dataminds_svcs_idm_password
      serviceAccountName: csi-provider

Please look into it and let me know if i miss anyting

**Comment by aramase** [comment]
Please follow the troubleshooting guide to look at the logs: https://secrets-store-csi-driver.sigs.k8s.io/troubleshooting#logging. There should more info about why it failed.

**Comment by srreddy2020** [comment]
Thanks for the reply Aramase,i could not find any use logs from the csi-driver pod.please see the output
![image](https://github.com/user-attachments/assets/d012fc40-d64e-43f9-8417-93806dbce5eb)

**Comment by aramase** [comment]
> 1)Will Csi-driver will create a secret without Mounting the Volume\VolumeMounts to the Pod?

No, it won't! It's documented here: https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret. If you only want to sync as k8s secret without mount, we're working on a new controller: https://github.com/kubernetes-sigs/secrets-store-sync-controller. It's currently alpha but give it a spin and report any issues you find there.

If you're using the driver to sync as k8s secrets, you'll still need to add the volume referencing the `SecretProviderClass` and the driver.

**Comment by srreddy2020** [comment]
Thank you aramase, after adding volume and Mount ,its created secret

**Comment by aramase** [comment]
Closing as issue is resolved.

/close
