### ISSUE TITLE
Add option to sync with Kubernetes secrets

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#167]
Ref: https://github.com/Azure/kubernetes-keyvault-flexvol/issues/140

**Comment by dmaterowski** [comment]
Is there any timeline / release plan, especially for this feature?

**Comment by ritazh** [comment]
We are working on this feature right now. Please subscribe and check back later.

**Comment by ibattat** [comment]
+1 any news on this feature?

**Comment by aramase** [comment]
#186 that adds support for this has been merged to master. This will be included in the next release v0.0.10
