### ISSUE TITLE
Add support for environment variable

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#168]
Ref: https://github.com/Azure/kubernetes-keyvault-flexvol/issues/28

**Comment by ritazh** [comment]
Closing this as it is now possible to set env var with the synced k8s secret feature: https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-set-env-var

**Comment by l-dalessandro** [comment]
@ritazh Can I use a secret stored/key/certs in mount path setting it like environment variable?
