### ISSUE TITLE
Annotations missing from the CSIDriver secrets-store.csi.k8s.io

### ISSUE THREAD

**Issue by burtlo** [kubernetes-sigs/secrets-store-csi-driver#170]
A pod that defines a volume that uses the  CSI driver `secrets-store.csi.k8s.io` is unable to find it. I noticed that the Helm chart created `secrets-store.csi.k8s.io` but there are no annotations with it so I think it is not addressable.

When I manually apply a CSIDriver definition the annotations are set for the CSIDriver.

- Is this because I am using Helm 3 to load this Helm chart?
- It there another way to reference the CSIDriver that this Helm chart creates?

## Steps to Reproduce

I cloned this repository.

```shell
$ git clone git clone git@github.com:kubernetes-sigs/secrets-store-csi-driver.git
```

Using helm 3, I installed the `secrets-store-csi-driver` Helm chart.

```shell
$ helm install csi-secrets-store secrets-store-csi-driver/charts/secrets-store-csi-driver
NAME: csi-secrets-store
LAST DEPLOYED: Fri Mar 13 01:06:37 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The Secrets Store CSI Driver is getting deployed to your cluster.

To verify that Secrets Store CSI Driver has started, run:

  kubectl --namespace=default get pods -l "app=secrets-store-csi-driver"

Now you can follow these steps https://github.com/kubernetes-sigs/secrets-store-csi-driver#use-the-secrets-store-csi-driver
to create a SecretProviderClass resource, and a deployment using the SecretProviderClass.
```

I verify that the CSI Driver, secrets-store-csi.k8s.io has been created.

```shell
$ kubectl describe CSIDriver secrets-store.csi.k8s.io
Name:         secrets-store.csi.k8s.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1beta1
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2020-03-13T16:35:32Z
  Resource Version:    1364
  Self Link:           /apis/storage.k8s.io/v1beta1/csidrivers/secrets-store.csi.k8s.io
  UID:                 439d2646-aa63-4054-9740-2392d9b006ce
Spec:
  Attach Required:    false
  Pod Info On Mount:  true
  Volume Lifecycle Modes:
    Ephemeral
Events:  <none>
```

I create a SecretProviderClass.

```shell
$ cat <<EOF | kubectl apply -f -
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-foo
spec:
  provider: vault
  parameters:
    roleName: "example-role"
    vaultAddress: "http://$VAULT_CLUSTER_IP:8200"
    vaultSkipTLSVerify: "true"
    objects:  |
      array:
        - |
          objectPath: "/secret/data/foo"
          objectName: "bar"
          objectVersion: ""
EOF
```

I create a pod.

```shell
$ cat <<EOF | kubectl apply -f -
kind: Pod
apiVersion: v1
metadata:
  name: nginx-3
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-foo"
EOF
```

The description of the pod displays the following warning:

```
Warning  FailedMount  47s (x14 over 13m) 
kubelet, minikube  MountVolume.SetUp failed for volume "secrets-store-inline" : 
kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io
not found in the list of registered CSI drivers
```

**Comment by aramase** [comment]
@burtlo Thank you opening the issue. The driver name change to `secrets-store.csi.k8s.io` instead of `secrets-store.csi.k8s.com` was recently merged. We are yet to publish a new release with the changes included. We'll be publishing a new image soon with the changes included. I'll update here when the new release is available today for you to try out.

**Comment by aramase** [comment]
@burtlo We just published a new [release](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.8) for the driver which includes the changes for the driver name. Please try out the latest charts/deployment and let us know if you have still have any issues.

**Comment by ritazh** [comment]
Closing this via the https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.8 release. Please reopen if this issue persists.
