### ISSUE TITLE
Helm 3 install instructions

### ISSUE THREAD

**Issue by gopher194** [kubernetes-sigs/secrets-store-csi-driver#182]
Hello, the instructions for install with Helm 3 (without Tiller) could be improved by giving more detailed instructions.
What worked for me was (Windows 10 Dev machine, AKS cluster target, Helm version 3.1.1):
- Download ZIP file from release:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/archive/v0.0.9.zip
- Unzip the archive locally,
- Run:
`$NAMESPACE="dev"`
`helm template csi-secrets-store C:\Downloads\secrets-store-csi-driver-0.0.9\charts\secrets-store-csi-driver --namespace $NAMESPACE > manifest.yml`
- then
`kubectl apply -f .\manifest.yml --validate=false`

**Comment by aramase** [comment]
@gopher194 Thank you for opening the issue. We'll update the instructions. 

For helm3, you should be able to directly install using -

`helm install csi-secrets-store <chart dir>` instead of generating the manifests.

**Comment by gopher194** [comment]
Agreed.
In all cases, you need to clone or download the repo in your current directory, and this step is not that clear in the instructions.
Without the `--validate=false`, I was getting this error:
`error validating data: ValidationError(CSIDriver.spec): unknown field "volumeLifecycleModes" in io.k8s.api.storage.v1beta1.CSIDriverSpec`

**Comment by aramase** [comment]
@gopher194 What is your kubernetes version? Can you post the output for `kubectl version`?

**Comment by gopher194** [comment]
Sure, thanks:
`PS C:\Users\eb> k version`
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"150f36044fe31bee3891b5a3fae69c17237e022c", GitTreeState:"clean", BuildDate:"2020-02-21T10:02:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by aramase** [comment]
@gopher194 I can't seem to recreate the issue -

```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2020-01-14T00:28:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
➜ helm install csi-secrets-store charts/secrets-store-csi-driver
NAME: csi-secrets-store
LAST DEPLOYED: Tue Apr 14 14:55:28 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The Secrets Store CSI Driver is getting deployed to your cluster.

To verify that Secrets Store CSI Driver has started, run:

  kubectl --namespace=default get pods -l "app=secrets-store-csi-driver"

Now you can follow these steps https://github.com/kubernetes-sigs/secrets-store-csi-driver#use-the-secrets-store-csi-driver
to create a SecretProviderClass resource, and a deployment using the SecretProviderClass.
```

The csi driver file checks the server k8s version in the template - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/csidriver.yaml#L8-L12

this is my helm version -
```
➜ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
