### ISSUE TITLE
Add finalizer

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#203]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When sync K8s secrets is enabled, the `SecretProviderClass` object can be deleted before the pods using it are deleted. 

**What did you expect to happen:**
When sync K8s secrets is enabled, deletion of the `SecretProviderClass` object should be blocked until pods using it are deleted or until the finalizers are removed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
[Release v0.0.12](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.12) switches to using `ownerReference` for secrets and also introduces new CRD `SecretProviderClassPodStatus` to track status. So adding a finalizer is no longer required.

/close
