### ISSUE TITLE
Match SecretProviderClass from same namespace as pod

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#223]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We should only match `SecretProviderClass` in the same namespace as the pod.

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/45d76c799f787b70de23051a271604a16aedf5cf/pkg/secrets-store/utils.go#L610-L612

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by iMoses** [comment]
I just discovered this bug as well..
Any estimations on a fix deployment?
I'd really appreciate it :)

**Comment by aramase** [comment]
@iMoses We can get the fix included in the next release. Feel free to open a PR if you would like to pick this issue.

**Comment by ritazh** [comment]
Related https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/60

**Comment by aramase** [comment]
/close

As this is duplicate of #60. Please check #60 to track progress for this issue.
