### ISSUE TITLE
Remove revision and heritage labels from helm charts

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#226]
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/34a978c51db6b048873167c9e2003c145d2f5f23/charts/secrets-store-csi-driver/templates/_helpers.tpl#L26-L33

- [ ] Remove `revision` and `heritage` from labels
- [ ] Add recommended labels - https://helm.sh/docs/chart_best_practices/labels/#standard-labels
- [ ] Test Upgrade of helm charts work with the changes

**Comment by snooyen** [comment]
I'd like to take this issue

**Comment by aramase** [comment]
Awesome! I'll assign this issue to you. If you have any questions, please feel free to post them or here or ping us on [#csi-secrets-store](https://kubernetes.slack.com/messages/csi-secrets-store) slack channel 

/assign @snooyen
