### ISSUE TITLE
How to make this volume mount required thing for the pod to start 

### ISSUE THREAD

**Issue by anujgeek** [kubernetes-sigs/secrets-store-csi-driver#228]
**Describe the solution you'd like**
I frequently see the following error when a pod is starting:
MountVolume.SetUp failed for volume "stage-kv-vlm" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers

This volume mount is a required piece for me, and I have a startup script that depends on it. However, I continue to see more events:
 Type     Reason          Age                   From                  Message
  ----     ------          ----                  ----                  -------
  Normal   Scheduled       <unknown>             default-scheduler     Successfully assigned fileroom/fileroom-57d84c6c67-5k4n4 to aksfr000000
  Warning  FailedMount     14m (x8 over 15m)     kubelet, aksfr000000  MountVolume.SetUp failed for volume "stage-kv-vlm" : rpc error: code = Unknown desc = CreateFile C:\k\secrets-store-csi-providers\azure\provider-azure.exe: The system cannot find the path specified.
  Warning  FailedMount     13m                   kubelet, aksfr000000  Unable to attach or mount volumes: unmounted volumes=[stage-kv-vlm], unattached volumes=[stage-kv-vlm default-token-dfbng]: timed out waiting for the condition
  Normal   Pulling         13m                   kubelet, aksfr000000  Pulling image "myimage"

How do I stop a pod from starting unless the volume mount is successful?
I'm using driver:v0.0.10 as driver:v0.0.11 was giving issues on windows node pools (aks, kubernetes version 1.18.2) 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): driver:v0.0.10
- Kubernetes version: (use `kubectl version`): 1.18.2

**Comment by aramase** [comment]
@anujgeek How are you installing the driver and provider? 

```
Warning FailedMount 14m (x8 over 15m) kubelet, aksfr000000 MountVolume.SetUp failed for volume "stage-kv-vlm" : rpc error: code = Unknown desc = CreateFile C:\k\secrets-store-csi-providers\azure\provider-azure.exe: The system cannot find the path specified.
```

Looks like you haven't installed the azure keyvault provider for windows. 

You can install the driver and azure provider using -

```
$ helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
$ helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name --set secrets-store-csi-driver.windows.enabled=true --set windows.enabled=true
```

More instructions are here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure

**Comment by anujgeek** [comment]
@aramase I have installed the the azure key vault using those steps only.
The volume works for me, but only after I do a rolling update on my app pods. The first time couple times, it always gives this error. Or something like ' cannot find driver in registered list'

**Comment by aramase** [comment]
@anujgeek That's probably because of the start up time. The windows images take time to get downloaded to the cluster, which means pods could take time to get scheduled. If you deploy the application pod after ensuing the driver and azure key vault provider are running, then you shouldn't see errors.

**Comment by anujgeek** [comment]
@aramase Got it. But is there a way I can make my app pod wait till the mount is available?

**Comment by aramase** [comment]
@anujgeek The pod is started only after the volume is mounted in the pod. In this case, the pod is referencing a volume that uses the csi driver. The application pods need to be deployed after the driver is deployed. If the driver isn't yet deployed, `kubelet` will retry the mount until it succeeds.

**Comment by aramase** [comment]
Closing this issue based on the comments above. Feel free to reopen if you have any questions.

/close
