### ISSUE TITLE
Support for multiple azure keyvaults

### ISSUE THREAD

**Issue by jferr** [kubernetes-sigs/secrets-store-csi-driver#229]
**more of a question that could lead into a feature request.  Apologies if I'm doing this wrong**

We would like to mount secrets to pods where the secrets for one pod might come from one azure keyvault and the secrets for another pod might come from a second azure keyvault. We may end up  having as many as 30 or so keyvaults. Is this possible today?**
[A clear and concise description of what you want to happen.]

**Comment by aramase** [comment]
@jferr That is possible today. You would need to create a `SecretProviderClass` for each pod and configure the [keyvault name](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/v1alpha1_secretproviderclass.yaml#L9) and [objects](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/v1alpha1_secretproviderclass.yaml#L11-L20).

**Comment by jferr** [comment]
thank you, closing issue
