### ISSUE TITLE
byPod status not updated with all pod uid when running at scale

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#230]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When running at scale, the `byPod` status field doesn't contain all the pod UIDs that reference the secret provider class. While testing with 100 pods as part of load test, on average only 15-20 pod UIDs are updated in the byPod status field.

**What did you expect to happen:**
All 100 podUIDs should be updated in `byPod` status field

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by ritazh** [comment]
Can you please run the same load test using https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/224

**Comment by aramase** [comment]
I was able to validate with #224 and see 100 `ownerReferences` updated in the secret for all the `SecretProviderClassPodStatus`.

**Comment by aramase** [comment]
/close

[Release v0.0.12](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.12) switches to using `ownerRef` for secret clean up. So `byPodStatus` is no longer used.
