### ISSUE TITLE
How does application spring boot application(application.yml files) access the values once the key or secret is mounted in the container file system 

### ISSUE THREAD

**Issue by cpatil7** [kubernetes-sigs/secrets-store-csi-driver#235]
Hey, 

I was able to successfully mount the files secrets on POD. Would be helpful if we have documentation/reference sample to demonstrate how we can consume mounted file secrets into spring boot application.

I got reference of below changes

reference spring-cloud-starter-kubernetes-config in pom.xml 
use spring.cloud.kubernetes.secrets.enabled and 
spring.cloud.kubernetes.secrets.paths=/mnt/secrets-store

But not sure what the next steps, what all code changes we need to make in-order to set the secrets values in application.yml file. I am not looking for setting these as environment variables

Regards,
Patil

**Comment by aramase** [comment]
/close

Since this is application specific and needs to be addressed outside the scope of this project.
