### ISSUE TITLE
Support SecretProviderClass from different namespace

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#242]
The default behavior with this [change](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/224/files#diff-a31c6f6257e17c698bbc44d4dbb22a7dR124) in master is to use `SecretProviderClass` only in same namespace as pod. 

If there is a requirement to access `SecretProviderClass` in a different namespace from the pod, Please feel free to chime in on this issue.

/kind feature

**Comment by Imamjanishaik** [comment]
secretProviderClassNamespace is not supported currently ?

**Comment by aramase** [comment]
That's right. `SecretProviderClass` is namespace scoped resource. This is in conformance with Kubernetes RBAC best practices to prevent privilege escalation.

**Comment by aramase** [comment]
/close

Closing this issue now as it's not something we want to support.

**Comment by ebuildy** [comment]
My 2 cents: `SecretProviderClass` must stay namespace scoped, we could create a new resource: `Cluster SecretProviderClass` cluster scoped
