### ISSUE TITLE
Update readme post next release

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#268]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
We should add the following:
- default value for `syncSecrets.enable` will be set to `false` after the next 2 releases (secure by default)
- update deployment instructions https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-sync-with-kubernetes-secrets to enable this feature

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
/assign @tam7t 

We should add this as best practices + bring it up in the next community call
