### ISSUE TITLE
Move crds to crds dir for helm3

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#286]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- Move crds from `templates` to `crds` which is the recommended way for installing crds using helm3
- Add `template/crds.yaml` with 

  ```yaml
  {{- if .Values.installCRDs }}
  {{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
    {{ $.Files.Get $path }}
  ---
  {{- end }}
  {{- end }}
  ```
`installCRDs` by default will be false so crd install using helm2 is skipped. If using helm2 then `--set installCRDs=true`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

/good-first-issue

**Comment by Evalle** [comment]
Hey @aramase I can work on it. 
/assign

**Comment by aramase** [comment]
/retitle Move crds to crds dir for helm3

- Helm 2 is no longer supported, so we can drop that
- Investigate using a separate helm chart for crds
- Other option is clean uninstall and then install as the crds dir is a new change

**Comment by ritazh** [comment]
Few issues with moving the crds to the crds dir in Helm chart:
- Helm will install the crds in the crds/ directory if the crds are not already installed. If the crds are installed, it will not validate that the version installed matches the served/stored versions specified in the manifests. On upgrade it doesn't touch the crds/ directory at all.
- cannot template the crd yamls in the crds dir
