### ISSUE TITLE
[helm chart] enable installation in disconnected / offline cluster

### ISSUE THREAD

**Issue by abdennour** [kubernetes-sigs/secrets-store-csi-driver#287]
**Describe the solution you'd like**

The Helm chart of this software does not provide a way to fetch images from private registry : 

- No Values for imagePullSecrets
- Some images are hard coded in templates.

**Anything else you would like to add:**

Offline cluster - disconnected cluster .. this is how enterprise work

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Kubernetes version: (use `kubectl version`): v1.17

**Comment by abdennour** [comment]
The PR is opened. @ritazh  for your review please!

https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/288

**Comment by aramase** [comment]
@abdennour Thank you for the PR. This change has already been completed with #260. The latest changes for the charts are in `manifest_staging/charts` dir and will be published as official helm chart with the release tomorrow.

/close

**Comment by abdennour** [comment]
@aramase  I don't agree . They are not the same.
#260 does not provide a way for assigning `imagePullSecrets` , while this PR provides.

**Comment by aramase** [comment]
@abdennour Please feel free to open a PR for adding image pull secrets. #260 covers the changes for image configuration. The changes for helm chart are to be made in manifest_staging/charts/secrets-store-csi-driver directory.
