### ISSUE TITLE
Unable to retrieve the certificate from Azure Key vault to Nginx ingress pod.

### ISSUE THREAD

**Issue by mansing2** [kubernetes-sigs/secrets-store-csi-driver#291]
Hi,

We are unable to retrieve the certificate from Azure Key vault to the Nginx ingress pod (of kind:Ingress) with the following YAML manifest but since the Volume field does not support the kind Ingress it keeps on failing. Would you able suggest please around this? 

We are able to get the secrets to the app pod by following the steps from https://github.com/HoussemDellai/aks-keyvault.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-test
spec:
  tls:
    - hosts:
      - foo.bar.com
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: tls-secret
  rules:
    - host: foo.bar.com
      http:
        paths:
        - path: /
          backend:
            # This assumes http-svc exists and routes to healthy endpoints
            serviceName: http-svc
            servicePort: 80
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "secret-provider-kv-certificate"```

**Comment by SatyKrish** [comment]
kind:Ingress is not a pod. It is simply a routing rule. Volumes can be mounted only on pods (kind:Deployment or kind:Pod). 

You can follow [this example](https://github.com/SatyKrish/aks-ingress-controller-tls/blob/master/aks-ingress-tls-demo/README.md) for retrieving TLS certificate for use with Ingress.

**Comment by aramase** [comment]
+1 to what @SatyKrish said.

Also, adding the doc link we have for examples with different providers - https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/sample/ingress-controller-tls

**Comment by mansing2** [comment]
Thank you @aramase @SatyKrish great help! Closing this issue.
