### ISSUE TITLE
Add e2e to test deployment yaml updates

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#297]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
- Consider using e2e-test-provider
- First setup tests with vault and then add e2e-test-provider

**Comment by aramase** [comment]
Closed with #669 

/close
