### ISSUE TITLE
Keyvault integration with AKS broken

### ISSUE THREAD

**Issue by iamsoorya** [kubernetes-sigs/secrets-store-csi-driver#299]
The Keyvault integration is broken with AKS. 

 
kubectl get pods -A|grep -I csi:
 ```
shrikanth_umadi@Azure:~$ kubectl get pods -A|grep -I csi
default         csi-secrets-store-provider-azure-zpdtl   1/1     Running   0          34d
default         csi-secrets-store-provider-azure-zql9j   1/1     Running   0          34d
default         csi-secrets-store-qp6zl                  3/3     Running   0          34d
default         csi-secrets-store-v77bb                  3/3     Running   0          34d
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Kubectl get pods -o wide:
 ```
shrikanth_umadi@Azure:~$ kubectl get pods -o wide
NAME                                     READY   STATUS    RESTARTS   AGE   IP              NODE                                   NOMINATED NODE   READINESS GATES
csi-secrets-store-provider-azure-zpdtl   1/1     Running   0          34d   10.141.113.11   aks-gdprhubnodes-31385122-vmss000003   <none>           <none>
csi-secrets-store-provider-azure-zql9j   1/1     Running   0          34d   10.141.113.30   aks-gdprhubnodes-31385122-vmss000004   <none>           <none>
csi-secrets-store-qp6zl                  3/3     Running   0          34d   10.141.113.20   aks-gdprhubnodes-31385122-vmss000004   <none>           <none>
csi-secrets-store-v77bb                  3/3     Running   0          34d   10.141.113.4    aks-gdprhubnodes-31385122-vmss000003   <none>           <none>
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Kubectl eventoutput:
 ```
ns-gdprhub-kc   8m32s       Warning   FailedMount               pod/nginx-flex-kv                            MountVolume.SetUp failed for volume "secrets-store-inline-gdprhub-kc" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
ns-gdprhub-kc   9m35s       Warning   FailedMount               pod/nginx-flex-kv                            MountVolume.SetUp failed for volume "default-token-j65xf" : failed to sync secret cache: timed out waiting for the condition
ns-gdprhub-kc   7m33s       Warning   FailedMount               pod/nginx-flex-kv                            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline-gdprhub-kc], unattached volumes=[secrets-store-inline-gdprhub-kc timezone-config default-token-j65xf]: timed out waiting for the condition
ns-gdprhub-kc   110s        Normal    Pulling                   pod/nginx-flex-kv                            Pulling image "nginx"
ns-gdprhub-kc   108s        Normal    Pulled                    pod/nginx-flex-kv                            Successfully pulled image "nginx"
ns-gdprhub-kc   108s        Normal    Created                   pod/nginx-flex-kv                            Created container nginx-flex-kv
ns-gdprhub-kc   108s        Normal    Started                   pod/nginx-flex-kv                            Started container nginx-flex-kv
ns-gdprhub-kc   110s        Warning   Unhealthy                 pod/nginx-flex-kv                            Liveness probe failed: Get http://10.141.113.9:8080/gdpr/index.html: dial tcp 10.141.113.9:8080: connect: connection refused
ns-gdprhub-kc   110s        Normal    Killing                   pod/nginx-flex-kv                            Container nginx-flex-kv failed liveness probe, will be restarted
ns-gdprhub-kc   8m14s       Normal    UpdatedLoadBalancer       service/s-gdprhub-kc                         Updated load balancer with new hosts
 ```
[csi-secrets-store.zip](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5107698/csi-secrets-store.zip)

**Comment by blessedwithsins** [comment]
@iamsoorya Thanks a ton.

[csi-secrets-store.zip](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5107710/csi-secrets-store.zip)
[KV logs.zip](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5107711/KV.logs.zip)
[nginx.zip](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5107712/nginx.zip)
[secretprovider.zip](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5107713/secretprovider.zip)

**Comment by aramase** [comment]
ping @iamsoorya for providing the above details so we can get to the bottom of the issue

**Comment by iamsoorya** [comment]
soorya@Azure:~$ kubectl get nodes -o wide
NAME                                   STATUS   ROLES   AGE   VERSION    INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-gdprhubnodes-31385122-vmss000003   Ready    agent   41d   v1.16.10   10.141.113.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-gdprhubnodes-31385122-vmss000004   Ready    agent   41d   v1.16.10   10.141.113.20   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
soorya@Azure:~$


soorya@Azure:~$ kubectl get csidriver -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1beta1
  kind: CSIDriver
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1beta1","kind":"CSIDriver","metadata":{"annotations":{},"name":"secrets-store.csi.k8s.io"},"spec":{"attachRequired":false,"podInfoOnMount":true,"volumeLifecycleModes":["Ephemeral"]}}
    creationTimestamp: "2020-05-02T15:10:25Z"
    name: secrets-store.csi.k8s.io
    resourceVersion: "34862"
    selfLink: /apis/storage.k8s.io/v1beta1/csidrivers/secrets-store.csi.k8s.io
    uid: f3789bd6-5f18-4e83-9253-ffa09cec659b
  spec:
    attachRequired: false
    podInfoOnMount: true
    volumeLifecycleModes:
    - Ephemeral
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
soorya@Azure:~$

**Comment by iamsoorya** [comment]
Are the driver pods running on the same node on which nginx-flex-kv is being deployed?

Ans: it may run or it might run on the same node. I have deleted that pod now. I will re-create it.

**Comment by aramase** [comment]
> Ans: it may run or it might run on the same node. I have deleted that pod now. I will re-create it.

Did you get a chance to confirm if the driver pods are running on the nodes where the workload is deployed. That is a requirement because `kubelet` invokes the `driver` pod running on the same node as the workload to initiate the volume mount.

**Comment by iamsoorya** [comment]
I will double check this. Are these pods running as daemon set?

**Comment by aramase** [comment]
> I will double check this. Are these pods running as daemon set?

That's right. The driver and provider pods run as a daemonsets. However if you have custom taints configured on the node, you would need to add tolerations for those taints.

**Comment by iamsoorya** [comment]
Shrikanth,

Can you please check this?

**Comment by shrikantumadi** [comment]
Cluster is with 2 nodes, driver pods and workload may or may not run same node because of two nodes. IS there a way to run both driver pods and workloads to run on same node?

**Comment by aramase** [comment]
The driver pods run as a daemonset, so they will automatically be deployed on every node in the cluster unless there is a taint on some node that's not tolerated by the driver pod.

**Comment by shrikantumadi** [comment]
In our case there is no any taint on nodes, but let us check and come back to you. Can you please help me with kubectl commands to check taint availability on nodes?

**Comment by aramase** [comment]
Could you provide the details requested here - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/299#issuecomment-678367870

**Comment by aramase** [comment]
@iamsoorya Is this still an issue? If it is could you provide the details requested in https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/299#issuecomment-678367870

**Comment by aramase** [comment]
Closing this issue because we haven't heard back in more than 30 days. Please feel free to open a new issue if the issue still exists.

/close
