### ISSUE TITLE
Option to add debug flag for provider

### ISSUE THREAD

**Issue by mitsutaka** [kubernetes-sigs/secrets-store-csi-driver#301]
**Describe the solution you'd like**
Flags of provider command are [fixed](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/pkg/secrets-store/nodeserver.go#L221-L226). As far as I saw, we don't have a way to add `--debug` flag for providers even they have.

Azure: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/cmd/main.go#L23
Vault: https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/master/main.go#L20

We should add an option to add a debug flag for the provider for debugging. This can be done by inheriting the CSI Driver's debug flag value. Since the provider is run from the CSI Driver, there seems reasonable.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.13
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
@mitsutaka We recently merged https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/280 which adds GRPC support for driver-provider communication.The PR continues to invoke the provider binary by default with an option to opt-in for using GRPC for provider. So going forward the expectation is for new providers and existing providers to implement the GRPC server changes. The current plan is to cut release `v0.0.14` with those GRPC changes, so providers can start implementing the changes for the server.

**Comment by mitsutaka** [comment]
@aramase I've read te PR. I totally agree with that is going to GRPC communication between csi-driver and provider. I confirmed that current provider flags are implemented in `MountRequest`. 

At least the provider will be daemonized and communicate with GRPC request and response, so I think that the feature on the csi-driver side will not be necessary. In other words, giving a debug flag to the provider pod(or sidecar container) enables a csi-driver independent approach. I understand that it is possible to debug by looking at the log of the provider container instead of via csi-driver.

I don't know what each provider author imagines about, but I believe it's probably the way to go. I'll leave it to you how to handle this issue.

**Comment by aramase** [comment]
Closing this issue as the driver is using gRPC to communicate with the provider. The debug flag/log level can be implemented at the provider.

/close
