### ISSUE TITLE
secrets are syncing with Azure vault

### ISSUE THREAD

**Issue by Dinesh558** [kubernetes-sigs/secrets-store-csi-driver#310]
1) Created sync (secretObjects) SecretProviderClass object  and able to retrieve secrets from Azure vault.
2) Able to mount these secrets to pods as volume  and referencing the secrets as env variables.
3) But when I edit the secret in Azure Vault, new version of secret is not getting reflected in pod. Either as environment variable nor at the mount point

**What did you expect to happen:**
When Azure vault secret is updated, it should be reflected in the pod.

**Anything else you would like to add:**
[SecretProviderClass.txt](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5219773/SecretProviderClass.txt)
[pod-sync.txt](https://github.com/kubernetes-sigs/secrets-store-csi-driver/files/5219783/pod-sync.txt)

**Which provider are you using:**
Azure Key Vault

- Secrets Store CSI Driver version: (use the image tag):  mcr.microsoft.com/k8s/csi/secrets-store/driver:v0.0.13
- Kubernetes version: (use `kubectl version`): 1.16.7

**Comment by aramase** [comment]
@Dinesh558 auto-rotation of the content in the mount and secret based on update in external secrets store is currently not supported. This feature is planned for v0.0.15 release which is tentatively planned for end of September.

With the current releases, you would need to delete the Kubernetes secret and then restart the application pod to fetch the latest content from Key Vault.

Please follow https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/125 for updates on this feature.

/close
