### ISSUE TITLE
Helm chart does not provide ability to add volume mounts

### ISSUE THREAD

**Issue by GlorifiedTypist** [kubernetes-sigs/secrets-store-csi-driver#315]
**Describe the solution you'd like**

- Helm chart does not provide ability to add volume mounts to be referenced by daemonset.

**Anything else you would like to add:**
This is useful when using a locally signed CA in non-mTLS environments. Such as for use with the Hasicorp vault provider (secrets-store-csi-driver-provider-vault).

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
@GlorifiedTypist Are you interested in opening a PR to support this in the helm charts?

**Comment by aramase** [comment]
@GlorifiedTypist Is this still required? The driver communicates with the provider using grpc instead of the binary. So these volume mounts will only be required for the provider.
