### ISSUE TITLE
Debug logs being written to stderr

### ISSUE THREAD

**Issue by marty2bell** [kubernetes-sigs/secrets-store-csi-driver#320]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

These logs from the secret store image seem to be written to sdterr which causes alerts in our monitoring solution.

time="2020-09-16T19:30:12Z" level=debug msg="GRPC request: "
time="2020-09-16T19:30:12Z" level=debug msg="GRPC response: ready:<value:true > "
time="2020-09-16T19:30:14Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"

**What did you expect to happen:**

Write debug logs to sdtout.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Also, is there a mechanism to turn off debug logs, tune the logging level to info for example? 

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

We are using this driver on AKS with Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.0.12
- Kubernetes version: (use `kubectl version`): 1.18.6

**Comment by aramase** [comment]
`logrus` by default writes all logs to stderr and there is no inherent way to configure it - https://github.com/sirupsen/logrus/issues/403. We might need to add the hooks to reconfigure this behavior.

@marty2bell You can disable debug logs by setting `--debug=false` for the `secrets-store` container - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/values.yaml#L101-L102

**Comment by marty2bell** [comment]
@aramase Thanks for the tip on disabling debug

**Comment by marty2bell** [comment]
Hey @aramase Any thoughts on how to address this as it's causing quite a bit of noise in our production environment?

Doesn't look like logrus is going to change for new features......

**Comment by aramase** [comment]
@marty2bell I think the right way to fix the problem is to switching to use `klog` for logging. I'll add this as part of the `v0.0.16` milestone.

**Comment by aramase** [comment]
/close

(With switch to `klog`. `klog` writes logs to stderr too. Changing the `io.Writer` for each log level results in duplication of logs)
