### ISSUE TITLE
Add new secret to existing secret-provider-class fails #234

### ISSUE THREAD

**Issue by mo-saeed** [kubernetes-sigs/secrets-store-csi-driver#321]
What steps did you take and what happened:

Create a secret provider class with list of secrets and apply it
Create deployment (with 2 replicas) which has the secrets in the provider class as ENV variables and apply it
Till now all works fine
Now I need to add new secret, so add it to azure keyvault
Add it to secret provider class and apply the changes
add a new env variable with the new secret in the deployment file and apply the changes
The deployment fails with the error ```Error: couldn't find key FOO1 in Secret k8s-development/k8s-secrets-development```

Then if I scale the deployment to zero then up back to 2, every thing works fine but ofcourse this is not acceptable solution coz it has downtime.

What did you expect to happen:
when adding a new secret in the provider class and the deployment, everything should work without any downtime

Which access mode did you use to access the Azure Key Vault instance:
Pod Identity

Environment:

Secrets Store CSI Driver version: v0.0.13
Azure Key Vault provider version: 1.6.2:
Kubernetes version: v1.16.10:
Cluster type: AKS:

**Comment by aramase** [comment]
@mo-saeed This is a known limitation - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store. The secret is created when the pod is created but there is no auto update currently. 

The secret needs to be deleted before the pods are restarted. The new secret that gets created will have all the new objects from `SecretProviderClass`.

The auto update of secret and mounted content is part of auto rotation feature that's planned for v0.0.15 release.

**Comment by Dyllaann** [comment]
The rotation reconciler has now been added, and version 0.0.16 has been released.
Unfortunately, the problem where the secret is not removed before pod restart/recreation is still present from what I am experiencing.

Was this specific case implemented in the reconciler or will it be added in a later stage?

**Comment by iamhritik** [comment]
In my case secret is not created when the pod is created and even when creating POD getting this error: Error: secret "test-secret-aws" not found @aramase 

---deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-3
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-deployment-sa
      volumes:
      - name: secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "test-aws-secrets"
      containers:
      - name: nginx-deploy-3
        image: nginx
        env:
         - name: MASTER_USERNAME
           valueFrom:
             secretKeyRef:
              name: test-secret-aws
              key: master_username
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret
          mountPath: "/mnt/secrets-store"
          readOnly: true
