### ISSUE TITLE
secrets rotation poll interval per SecretProviderClass

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#322]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/303 implements the secret auto rotation feature. This rotation reconciler is essentially a periodic check that's triggered based on the duration configured in `--rotation-poll-interval` (default: `2m`).

Opening this issue to further discuss on the following comment thread - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/303#discussion_r486567950

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by gobins** [comment]
Looks like this has been already in discussion. Just adding some requirements that I have also come across. There are certain secrets which are updated very infrequently and it seems unnecessary to use the poll interval from the driver to keep polling for these secrets. Would be nice if we could override it at the SecretProviderClass. There is always that option to apply this logic and not do anything(call secret store) using metadata inside the provider. Just wanted to check if there was any further discussions on this.
