### ISSUE TITLE
Update otel to latest version

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#324]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- Update otel dependency to latest release 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

/good-first-issue

**Comment by Evalle** [comment]
I can take a look at it /assign

**Comment by Evalle** [comment]
@aramase it looks like the latest version is https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.12.0
Any guidance of how to update it for `secrets-store-csi-driver` project in "the right way"?

**Comment by aramase** [comment]
@Evalle Thank you for picking this up. 

> @aramase it looks like the latest version is https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.12.0
Any guidance of how to update it for secrets-store-csi-driver project in "the right way"?

We should update to the latest available stable release - `v0.12.0`. You can start off by updating the go.mod file to pick up the latest version. I took a look at the latest release and the packages have been reorganized. After go.mod you'll need to update the following files to pick up the latest changes - 

1. https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/pkg/secrets-store/stats_reporter.go
2. https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/pkg/rotation/stats_reporter.go
3. https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/pkg/metrics

**Comment by Evalle** [comment]
It's harder than I thought and it requires deeper golang knowledge. Feel free to assign this issue.

**Comment by vladdy** [comment]
I'll check this /assign

**Comment by aramase** [comment]
@vladdy No rush, but let me know if you need any help with the PR.
