### ISSUE TITLE
Add feature matrix for providers

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#333]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
- Windows
- Sync as Kubernetes secret
- Rotation
- Service account volume projection
