### ISSUE TITLE
Switch to klog

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#347]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Switch to klog for logging so we can get features like json logging.

- [ ] Update to using klog.
- [ ] Audit current logging to ensure there are sufficient logs indicating current status/errors.
- [ ] Configurable log verbosity

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1602-structured-logging/README.md
