### ISSUE TITLE
[secrets rotation] exclude the terminated pods from the secrets rotation

### ISSUE THREAD

**Issue by mo-saeed** [kubernetes-sigs/secrets-store-csi-driver#354]
**What steps did you take and what happened:**

we have right now thousands of logs generated for the terminated pods with failed to reconcile secrets error, and this is harming badly our log clusters plus it makes logs unreadable and the important logs are lost.

Can you please exclude the secret rotation mechanism for the terminated pods?

**What did you expect to happen:**
no secret rotation for the terminated pods

**Which provider are you using:**
Azure key vault

**Environment:**

- Secrets Store CSI Driver version: latest
- Kubernetes version: (use `kubectl version`): 1.17.11

**Comment by aramase** [comment]
Closing this with 
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/373
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/365

These will be included as part of `v0.0.17` release

/close

**Comment by pierluigilenoci** [comment]
@aramase Thank you!

**Comment by pierluigilenoci** [comment]
@aramase is there an approximated/expected release date for `v0.0.17`?
