### ISSUE TITLE
Fix e2e failure

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#355]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Getting consistent e2e failures from previous [runs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/348/pull-secrets-store-csi-driver-e2e-vault/1318819236537176064/build-log.txt):

```
not ok 13 Test Namespaced scope SecretProviderClass - Sync with K8s secrets - read secret from pod, read K8s secret, read env var, check secret ownerReferences
# (in test file test/bats/vault.bats, line 257)
#   `[[ "$result" -eq 2 ]]' failed
# Unable to use a TTY - input is not a terminal or the right kind of file
```
We should do the following:
1. Fix the TTY issue by removing `-t`
2. Print `$result` when failed
3. Is this a false positive?

This is blocking PRs like https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/348

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
@ritazh PTAL at https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/352. It contains the fixes for the TTY issue.
