### ISSUE TITLE
Switch to using official images for containers

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#357]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The `node-driver-registrar` and `liveness-probe` container images are currently referenced from mcr for Windows and quay registry for Linux. 

`k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1` and `k8s.gcr.io/sig-storage/livenessprobe:v2.1.0` container images now support multi-arch. We should switch the images in the [manifest_staging](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/manifest_staging) dir to use the official images for linux and windows.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Releases:
https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.1.0
https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.0.1

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

/good-first-issue
/kind cleanup

**Comment by Evalle** [comment]
I can take care of this /assign
