### ISSUE TITLE
Optionally just temporarily mount secrets (or make them deletable)?

### ISSUE THREAD

**Issue by DonMartin76** [kubernetes-sigs/secrets-store-csi-driver#36]
As really briefly outlined at KubeCon: It would be super awesome if it would be possible to just have the secrets mounted to the pod for a very limited amount of time, just enough to pick them up and store them in memory.

The **use case** for this would typically be things like database credentials - the pod starts, picks up the credential, and then it wouldn't need it anymore. It feels (almost) just as wrong as using environment variables to leave credentials laying around inside the pod as a permanent mount; anybody who would be able to open up a terminal (or similar) inside the container would be able to read them out.

Having the credentials only at startup could prevent these to leak too easily. Admitted, they would probably still be in memory then, but reading out memory from a running process is not that easy, especially if you don't have root rights inside the container.

### Implementation options
* Have a certain amount of time in which the secrets are available
* Couple it e.g. to pod readiness, and take away the credentials when the pod has signalized it's ready (and thus has already read the credentials)
* Allow for deletion of the credential files; the process can then simply delete the credential file when it has read them

This enhancement is inspired by the way how HashiCorp Vault can handle secrets: Giving out one time access tokens to retrieve the secrets directly from vault; even if this one time token leaks, nobody can make use of it, as it has already been used. This proposal would serve the same type of purpose - making sure it's as difficult as possible to steal your credentials, even if you happen to get access to the running pod.

**Comment by sinhaaks** [comment]
Hi @DonMartin76 ,
Can I work on this feature ?

**Comment by nilekhc** [comment]
> Hi @DonMartin76 , Can I work on this feature ?

Hi @sinhaaks Thanks for your interest. Could you write a proposal for this implementation? We can discuss it in our [next community call](https://docs.google.com/document/d/1q74nboAg0GSPcom3kLWCIoWg43Qg3mr306KNL58f2hg) on 8/18.
