### ISSUE TITLE
Secrets not properly synchronized when VAULT name changes but k8s name is reused

### ISSUE THREAD

**Issue by doug-papenthien-by** [kubernetes-sigs/secrets-store-csi-driver#364]
**What steps did you take and what happened:**
During a recent refactoring of some code, we updated our service configuration to use a different secret name from our Azure Key Vault.  However, the corresponding k8s secret name remains unchanged.  When this new service configuration is deployed, the k8s secret value is *NOT* being updated with the new value.  Interestingly, the secret value in the mounted file system *IS* properly updated.

Scaling the replica set down to 0 replicas and then back up to 1 corrects the issue as the k8s is re-created.

**What did you expect to happen:**
When the remote secret backing a k8s is changed, it should be synchronized in k8s.

**Anything else you would like to add:**
I've reported this against v0.0.13.  However, I also tested with the latest version and experienced the same behavior.

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): driver:v0.0.13
- Kubernetes version: (use `kubectl version`): 1.16.15 (AKS)

**Comment by aramase** [comment]
@doug-papenthien-by So this is a known limitation - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store. The Kubernetes secret is created the first time a pod referencing it is created. The secret data is mirrored based on the content in mount. 

To enable update of the created Kuberentes secret and the mounted contents, we have introduced secret rotation alpha feature in `v0.0.16`. 

Docs on how to enable secret rotation -
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.rotation.md

If auto rotation is enabled, updates to `SecretProviderClass` will be honored.

**Comment by doug-papenthien-by** [comment]
Hmm, I thought the scenario I'm reporting was slightly different than this, but after reading your first link I'm not so sure anymore.  In my case, we've kept the same name of the k8s secret but are mapping it to a brand new name in the remote key vault.  A new pod is created for this deployment because we have an annotation on the deployment that is a hash of the secret configuration.  This way changes are applied immediately even if the only thing that changes in the deployment is related to the secrets.  The behavior I observed the is that the mounted content was properly updated to the new value, but not the k8s secret.  This isn't quite what's documented in your link where neither are expected to be updated.  I did not think to check the value of the environment variable.

Are there any known issues with the rotation feature?  If the behavior I've described is expected, we'll have to weigh our options between upgrading and trying out the rotation feature or ensuring secrets are deleted before new deployments.

**Comment by aramase** [comment]
> Hmm, I thought the scenario I'm reporting was slightly different than this, but after reading your first link I'm not so sure anymore. In my case, we've kept the same name of the k8s secret but are mapping it to a brand new name in the remote key vault. A new pod is created for this deployment because we have an annotation on the deployment that is a hash of the secret configuration. This way changes are applied immediately even if the only thing that changes in the deployment is related to the secrets. The behavior I observed the is that the mounted content was properly updated to the new value, but not the k8s secret. This isn't quite what's documented in your link where neither are expected to be updated. I did not think to check the value of the environment variable.


The Kubernetes secret is created by reading the files from the pod mount. The secret by default is not updated with new pod is created because there would be a discrepancy in the secret objects and the mounted content in case of old pods. However with auto rotation we periodically refresh the mount for all pods and then subsequently the Kubernetes secret. 

> Are there any known issues with the rotation feature? If the behavior I've described is expected, we'll have to weigh our options between upgrading and trying out the rotation feature or ensuring secrets are deleted before new deployments.

The auto rotation feature is an alpha feature that was added in the latest release `v0.0.16`. We are gathering feedback from users. The behavior you pointed out is expected. Without the upgrade as documented, you'll need to delete the Kubernetes secret and then restart/deploy new pods. The new Kubernetes secret will be created with the latest content from the new pod.

**Comment by doug-papenthien-by** [comment]
Thanks for the detailed info.
