### ISSUE TITLE
cleanup csi socket as part of shutdown from plugins dir

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#367]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
`secrets-store` container should clean up the `csi.sock` from plugins dir as part of graceful shutdown

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by tam7t** [comment]
If help is needed here I can look into this.

**Comment by aramase** [comment]
@tam7t Go for it! The `node-driver-registrar` cleans up the `registration.sock`. So this one would specifically be for the `csi.sock` that the driver is listening on.
