### ISSUE TITLE
Ability to run e2e tests locally for each provider

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#368]
/kind documentation

**Comment by helayoty** [comment]
- [ ] Azure: Add script to generate the necessary objects
- [ ] Azure: Test user can run the e2e test toward their own Keyvault/ Service Principal 
- [ ] GCP: Add script to generate the necessary objects 
- [ ] GCP: Test user can run the e2e test toward their own key store/ Service Account
- [ ] Update documentation

**Comment by helayoty** [comment]
@nilekhc @aramase  may I know the stats of the e2e tests now? I'd like to continue the efforts if there is any still in progress.

**Comment by nilekhc** [comment]
Hey @helayoty, Thanks for the ping.

I am not fully aware about the context behind this issue. But, we have added [e2e-mock-provider](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/test/e2eprovider) for tests. The idea behind this is to be able to test driver functionality without relying on any specific provider.

Is this something we should promote to test driver functionality on local? I am happy to discuss this offline and/or in our community call.

**Comment by aramase** [comment]
The primary focus of this issue was to document how to run the e2e tests with different supported providers. As Nilekh, mentioned we now have a `e2e-provider` for validating all the driver features. Going forward the e2e test suite will be enhanced and new tests added while the provider test suite will be trimmed down to the bare minimum. The providers tests will only be used to validate the contract defined between driver-provider is still intact.

Given these changes, I think the scope of this issue is now just adding documentation on how to install the `e2e-provider` using make targets and running the tests with the default/newly built driver.

**Comment by helayoty** [comment]
> The primary focus of this issue was to document how to run the e2e tests with different supported providers. As Nilekh, mentioned we now have a `e2e-provider` for validating all the driver features. Going forward the e2e test suite will be enhanced and new tests added while the provider test suite will be trimmed down to the bare minimum. The providers tests will only be used to validate the contract defined between driver-provider is still intact.
> 
> Given these changes, I think the scope of this issue is now just adding documentation on how to install the `e2e-provider` using make targets and running the tests with the default/newly built driver.

Thanks for the clarification.
