### ISSUE TITLE
Can't fetch secret in a namespace different from the one of the csi driver

### ISSUE THREAD

**Issue by romina2001** [kubernetes-sigs/secrets-store-csi-driver#410]
# Azure documentation issue guidance
Ref: https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes

Hi,

I have followed the documentation in order to integrate AKS with AKV and all works well if the pod is in the same namespace with the csi-driver, and the SecretProviderClass .
If the pod is in a different namespace, together with the SecretProviderClass I get the following error:

```

 Type     Reason       Age                   From                                    Message
  ----     ------       ----                  ----                                    -------
  Warning  FailedMount  52m (x107 over 20h)   kubelet, aks-nodes-19772276-vmss000000  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-qcdql config-file]: timed out waiting for the condition
  Warning  FailedMount  31m (x302 over 20h)   kubelet, aks-nodes-19772276-vmss000000  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[config-file secrets-store-inline default-token-qcdql]: timed out waiting for the condition
  Warning  FailedMount  22m (x119 over 20h)   kubelet, aks-nodes-19772276-vmss000000  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[default-token-qcdql config-file secrets-store-inline]: timed out waiting for the condition
  Warning  FailedMount  3m1s (x610 over 20h)  kubelet, aks-nodes-19772276-vmss000000  MountVolume.SetUp failed for volume "secrets-store-inline" : fetching NodePublishSecretRef dev/secrets-store-creds failed: kubernetes.io/csi: failed to find the secret secrets-store-creds in the namespace dev with error: secrets "secrets-store-creds" not found

```

Does the driver needs to be installed in all namespaces so that the pods from the other namespaces can have access to the secrets from the keyvault?
I need that all my pods, from all namespaces to have access to the secrets.

**Comment by aramase** [comment]
@romina2001 If using Service Principal for auth, the Kubernetes secrets containing the credentials need to be created in the same namespace as the application pod. The secret name provided in `nodePublishSecretRef`  is only looked up in the same namespace as the app pod to conform with best practices.

**Comment by romina2001** [comment]
Thank you. Yes it works if the secret is in the same namespace.
