### ISSUE TITLE
Improvement about the port of driver metrics endpoint

### ISSUE THREAD

**Issue by ZhijunZhao** [kubernetes-sigs/secrets-store-csi-driver#411]
**Describe the solution you'd like**
I'm using Prometheus to gather the driver metrics. I thought parameter `metricsAddr` can control the port of the metrics endpoint. However, this endpoint only exposes controller related metrics. 

With the help of @mitsutaka, I realize that the port is [hard-coded](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/pkg/metrics/exporter.go#L26) as `8888`.  

I think there should be
1. Document about the port of the driver metrics. 
2. Parameter for overriding the port number. 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  v0.0.18

**Comment by aramase** [comment]
@ZhijunZhao You can configure the prometheus port using:

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/efe288d26b8adc2d4f8e86769b678257ec7be5e1/pkg/metrics/exporter.go#L26

This value isn't exposed in the helm chart. We can get this added in the next release.
