### ISSUE TITLE
Facing issue in installing secrets-store-csi-driver with kubernetes 1.16

### ISSUE THREAD

**Issue by ptilloo** [kubernetes-sigs/secrets-store-csi-driver#427]
Hi - I am facing issue with installing secrets-store-csi-driver in my Kubernetes cluster 1.16.

.\helm install --name csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace csi
Error: render error in "secrets-store-csi-driver/templates/csidriver.yaml": template: secrets-store-csi-driver/templates/_helpers.tpl:40:45: executing "csidriver.apiVersion" at <.Capabilities.KubeVersion.Version>: can't evaluate field Version in type *version.Info

 .\helm install --name csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace csi --de
bug
[debug] Created tunnel using local port: '63250'

[debug] SERVER: "127.0.0.1:63250"

[debug] Original chart version: ""
[debug] Fetched secrets-store-csi-driver/secrets-store-csi-driver to C:\Users\Piyush.Tilloo\.helm\cache\archive\secrets-store-csi-driver-0.0.19.tgz

[debug] CHART PATH: C:\Users\Piyush.Tilloo\.helm\cache\archive\secrets-store-csi-driver-0.0.19.tgz

Error: render error in "secrets-store-csi-driver/templates/csidriver.yaml": template: secrets-store-csi-driver/templates/_helpers.tpl:40:45: executing "csidriver.apiVersion" at <.Capabilities.KubeVersion.Version>: can't evaluate field Version in type *version.Info

I am using below helm :

Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

Any thoughts , help on the above issue much appreciated.

**Comment by aramase** [comment]
@ptilloo Helm3 is a prerequisite for the charts: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/charts/secrets-store-csi-driver#prerequisites.

**Comment by ptilloo** [comment]
Thank You for clarifying @aramase.  Another question I had was in the File - secretproviderclass.yaml - like :

# This is a SecretProviderClass example using a service principal to access Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "kvname"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          **objectName: secret1**
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key1
          objectType: key
          objectVersion: ""
    tenantId: "tid"                    # the tenant ID of the KeyVault

What is  -  objectName: secret1 , what should be **secret1** .  May be a novice question as I am trying this for the first time. Any clarity will help.

Thanks

**Comment by aramase** [comment]
@ptilloo Those are the secret/key/certificate object names that you want to retrieve from keyvault. Here is the doc on the configuration values: https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/usage/

Installation doc: https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/

**Comment by ptilloo** [comment]
@aramase  - Thanks so much for the help.

**Comment by aramase** [comment]
Happy to help! Closing this issue now as there is nothing outstanding.

Please feel free to open an issue [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) if you have any questions specifically for the Azure provider.

/close
