### ISSUE TITLE
regular liveness-probe OOM

### ISSUE THREAD

**Issue by aelmanaa** [kubernetes-sigs/secrets-store-csi-driver#443]
**What steps did you take and what happened:**
Hello,

we are running secret-store-csi on AKS and we notice regular restarts of containers due to OOM.
Just checked Azure monitoring tools and indeed I see that for the past 30 days, memory(Memory working set) increases until OOM. Is there a memory leak?

![image](https://user-images.githubusercontent.com/4503543/107024340-39fd4b80-67a8-11eb-9f38-9fa565efec58.png)

**What did you expect to happen:**
sable memory utilization , specially if the purpose of this container is only to provide liveness-probe capability

**Anything else you would like to add:**
N/A

**Which provider are you using:**
AZure key vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
k8s.gcr.io/csi-secrets-store/driver:v0.0.17
k8s.gcr.io/sig-storage/livenessprobe:v2.1.0 
- Kubernetes version: (use `kubectl version`): 1.19.3

**Comment by aramase** [comment]
@aelmanaa Could you use the latest version of the driver [v0.0.19](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.19) and liveness-probe? We've updated the liveness-probe image to `v2.2.0` with the latest release which contains fixes for memory leaks ([PR](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/424))

The `liveness-probe` container is owned by the Kubernetes CSI team and is hosted here: https://github.com/kubernetes-csi/livenessprobe

**Comment by ritazh** [comment]
@aramase Can you pls add a ❗ :exclamation: to the release note of https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.19 to highlight this fix?

**Comment by aramase** [comment]
> @aramase Can you pls add a ❗ to the release note of https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.19 to highlight this fix?

Done! Also, added a warning note with reference to the fix in the liveness-probe repo.

**Comment by aramase** [comment]
Closing this issue as the latest `liveness-probe` image contains the fix. Please feel free to reopen if you find any issues after upgrading to the latest liveness-probe image.

/close
