### ISSUE TITLE
Error deploying app after adding secret-store-csi-driver and using Helm 3

### ISSUE THREAD

**Issue by ptilloo** [kubernetes-sigs/secrets-store-csi-driver#447]
@ptilloo Helm3 is a prerequisite for the charts: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/charts/secrets-store-csi-driver#prerequisites.

_Originally posted by @aramase in https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/427#issuecomment-763785466_

**Comment by ptilloo** [comment]
Hi @aramase  - After sucessfully installing the - secrets-store-csi-driver - I am faced with a wired issue when I try do do the deployment off my application using helm3. The helm install fails while reading the yaml file from the backend_chart. I have a deployment.yaml which was running fine with helm 2 but I see this wired error in helm 3, i am using helm 3.5.2.

**Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field "options" in io.k8s.api.core.v1.Volume
helm.go:81: [debug] error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field "options" in io.k8s.api.core.v1.Volume**

Below is my deployment file snippet where this issue is coming from: 

 volumes:
      - name: env
        configMap:
          name: '{{ template "fullname" . }}-env-config'
      - name: keyvault
        csi:
          driver: "secrets-store.csi.k8s.io" # Add csi driver
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname
          nodePublishSecretRef:
            name: kvcreds
        options:
          usepodidentity: "false"
          keyvaultname: "{{ .Values.keyvault }}"
          keyvaultobjectnames: "auth0-client-secret;postgres-app-pwd;redis-secret;insights-key;storage-container-string"
          keyvaultobjecttypes: secret;secret;secret;secret;secret
          resourcegroup: "{{ .Values.resourcegroup }}"
          subscriptionid: "{{ .Values.subscriptionid }}"
          tenantid: "{{ .Values.tenantid }}"

Any help or pointer to resolve it will help.

Thanks

**Comment by aramase** [comment]
@ptilloo Why are the options field in the volumes? I'm not sure how your application helm chart is structured but `options` is not a field in csi. Since it's a unknown value, it'll fail validation. All those configurations you've in options are to be set in the `SecretProviderClass`.

**Comment by ptilloo** [comment]
@aramase  - We are upgrading from K8 1.15 to 1.16 which hence changes the way our application connects with the Key Vault store in Azure, the deployment yamls are old when flexVolume  was used, the options field was thus present in the deployment yaml when flexVolume  was in place now since from K8 1.16 flexVolume got replaced by csi , so I edited the yaml removing the flexVolume and add csi but looks like missed to remove or edit  the options field section, hence the deployment was complaining. I removed it moved it to SecretProvider class not the error is gone.

**Comment by aramase** [comment]
@ptilloo The Secrets Store CSI Driver functions differently from the keyvault flexvolume solution. The provider specific parameters are configured using a custom resource `SecretProviderClass`. Please take a look at the docs for more detailed info on how to configure.

https://secrets-store-csi-driver.sigs.k8s.io/
https://azure.github.io/secrets-store-csi-driver-provider-azure/

**Comment by ptilloo** [comment]
@aramase  - Thanks for the links.  I have a  - secretproviderclass.yaml which looks like this  :

     apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "false"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: ""  # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "{{ .Values.keyvault }}"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: postgres-su-pwd
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: postgres-admin-user
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: insights-key
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: auth0-client-secret
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: redis-secret
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: postgres-app-pwd
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: storage-container-string
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: rootCrt
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: postgres-adfuser-pwd
          objectAlias: ""     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty        
    resourceGroup: "{{ .Values.resourcegroup }}"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "{{ .Values.subscriptionid }}"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "{{ .Values.tenantid }}"                 # the tenant ID of the KeyVault

**Comment by aramase** [comment]
@ptilloo Could you please check the logs for the driver and provider pods as mentioned in the troubleshooting guide? We've a standard walkthrough guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/ that'll help you with the steps as you try out the project.

**Comment by ptilloo** [comment]
@aramase  - I figured out the issue it was a trivial issue where the Key vault name in the values.yaml was incorrect.
Thanks the all the documents though. I am closing this issue
