### ISSUE TITLE
Add upgrade to e2e

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#457]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
A e2e job that tests upgrade from n to n+1 via helm

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by tam7t** [comment]
1. install the release chart (version in `makefile`)
2. run the test suite
3. install the staging chart
4. run the test suite

**Comment by nilekhc** [comment]
I'll take this.
