### ISSUE TITLE
Optimize watches and Kube API calls 

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#459]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- [ ] Enable filtered watches for pods, secrets, secretproviderclasspodstatus
   - `controller-runtime` doesn't provide an option to do filtered watches for resources. This would require vendor-ing the cache package and maintaining changes in the driver.
   - Implementation in progress in #458 
- [ ] Evaluate and optimize API calls for PATCH
- [ ] Document load test results in large clusters before and after optimization
- [ ] Enable filtered watch in rotation reconciler for secrets

All filtered watches should be enabled with a feature flag and can be made default after n+2 releases. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by andyzhangx** [comment]
cc @ZeroMagic
