### ISSUE TITLE
Helm chart doesn't use kube-system namespace by default

### ISSUE THREAD

**Issue by andrebriggs** [kubernetes-sigs/secrets-store-csi-driver#463]
**What steps did you take and what happened:**
Ran the latest Helm chart using Helm 3

```bash
$ helm template blah . > secret-store.yaml
$ cat secret-store.yaml
---
# Source: secrets-store-csi-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: default
  labels:
    app.kubernetes.io/instance: "blah"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "secrets-store-csi-driver"
    app.kubernetes.io/version: "0.0.20"
    app: secrets-store-csi-driver
    helm.sh/chart: "secrets-store-csi-driver-0.0.20"
# (snip...)
```
**What did you expect to happen:**
Expected to see `ServiceAccount` object being the `kube-system` namespace based upon #375. From my understanding this is preferred for all objects that can be namespace according to #386 

I suggest making a note in the Helm chart [README.md](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/charts/secrets-store-csi-driver#configuration) recommending folks set the namespace to `kube-system` and/or add a variable in `values.yaml` to optionally set  `kube-system` to be the default namespace.

**Comment by aramase** [comment]
Closed with #505 

/close
