### ISSUE TITLE
POD security policy preventing root user image: Use Image as Non Root User

### ISSUE THREAD

**Issue by ShatadruDas** [kubernetes-sigs/secrets-store-csi-driver#477]
I am facing a problem with Secret store CSI driver in Kubernetes. Actually there is a security policy POD running, in our kubernetes cluster which mandates all images to be running as non root user.

But while security POD scans the below images it finds out that, image have root user privileges. How can we run these images as **non root user** or is there similar images with non-root user please.

csi-secrets-store:v0.0.20

csi-node-driver-registrar:v2.1.0

csi-liveness-probe:v2.2.0

refer here : https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/deploy/secrets-store-csi-driver.yaml

Deploying CSI drivers using YAMLs as in below doc,

https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html

**Comment by aramase** [comment]
@ShatadruDas The CSI driver needs to run as root to be able to mount the volumes in the pod.

**Comment by aramase** [comment]
Closing this issue because the CSI driver needs privileges to be able to perform mount operations.

/close
