### ISSUE TITLE
Get list of certificates by name (including all older versions)

### ISSUE THREAD

**Issue by kchilka-msft** [kubernetes-sigs/secrets-store-csi-driver#485]
I would like to make a request to have a functionality where all the versions of a certificate can be read from the keyvault. At the moment, when specifying the certificate details in the yaml file, we can specify the objectVersion but when a certificate auto-rotates, there involves a manual step to update the yaml file with the new objectVersion and redeploy it. It would be a nice to have if the current & older versions of a certificate be read without having to manually update the yaml file.

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
@kchilka-msft The Secrets Store CSI Driver supports auto rotation of the mounted content and Kubernetes secret. If the `objectVersion` is not specified, the csi driver will periodically fetch the latest content from the external secrets store and update the mount and Kubernetes secret. 

Please refer to https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html on how to enable auto rotation. 

Note: If the `objectVersion` is explicitly set in the `SecretProviderClass`, then only that version will be fetched.

**Comment by kchilka-msft** [comment]
hi @aramase thanks for the response. I am able to pull the latest auto rotated cert but I have a scenario where we need the latest auto rotate cert as well as the older version of the cert before it was auto rotated. For ex:

if C1 = current cert 
and after auto-rotation C2 = current cert,
then we need to pull both C1 & C2. 

From what I have read so far, I dont think it is possible, so I was wondering if this is something that is possible to do and could be added as a potential request.

**Comment by kchilka-msft** [comment]
the use case is: we have a process where when we get a request, a token is issued to the client (and this token is specific to the available cert itself) and it is cached on the client side for x number of days. And in a scenario when a cert gets auto-rotated and if the client happens to use the cached token that was issued with the older cert (say C1 from above example) it might fail to validate the token. As far as handling 2 versions of the same cert goes, as long as we can pull the certs from the keyvault in the file system we can use the NotAfter property to identify which is the newer/older cert

**Comment by kchilka-msft** [comment]
hi @aramase - did you get a chance to look further into this? thanks!

**Comment by aramase** [comment]
@kchilka-msft Getting all versions of a secret might be possible but that would require `List` permissions (for Azure Keyvault) to be able to get the all the available versions. Updating the `SecretProviderClass` is now more scoped to user taking the necessary actions.

**Comment by kchilka-msft** [comment]
@aramase - that's great! I can have the List permissions enabled on the Azure Keyvault. I was trying to find if there's anything specific changes that I need to make to the SecretProviderClass file but couldn't find anything special. I was referring to [this file ](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/keyvault-certs/v1alpha1_secretproviderclass_certs.yaml). So can I assume that if I just specify something like below without the objectVersion, it will pull all the available version?
![image](https://user-images.githubusercontent.com/69543850/114761377-3d1b3780-9d15-11eb-9557-684084d80d3d.png)

**Comment by kchilka-msft** [comment]
@aramase - can you please provide us documentation on how to get all the available versions of a certificate from Azure Keyvault

**Comment by aramase** [comment]
@kchilka-msft Getting all available versions of an object is not a feature that we support. Today if you provide the `objectVersion`, the exact version will be fetched. If no `objectVersion` is provided, then the latest will be fetched. This is a provider specific feature request, so please open an issue in  https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues with the feature request if you request isn't already represented in any of the exsiting GitHub issues.

**Comment by kchilka-msft** [comment]
@aramase - ahh okay! from your previous comment I assumed it is possible. I will open up a feature request

**Comment by aramase** [comment]
thank you! I'll close this issue now. Feel free to reopen if you have any questions.

/close
