### ISSUE TITLE
secrets reconciling doesn't respect owner references

### ISSUE THREAD

**Issue by terinjokes** [kubernetes-sigs/secrets-store-csi-driver#499]
**What steps did you take and what happened:**

The reconciler of `SecretObjects` does not respect owner references of existing secrets, and does not set references on secrets it creates. This can cause this controller to clobber secrets owned by other controllers.

**What did you expect to happen:**

Controller should check for existing owner references with `controller: true` before patching secrets. The controller should also set controller owner references on secrets it creates.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v2.1.0

**Comment by aramase** [comment]
> The reconciler of SecretObjects does not respect owner references of existing secrets, and does not set references on secrets it creates. This can cause this controller to clobber secrets owned by other controllers.

Are you referring to the owner references of the Kubernetes secrets created by the CSI driver as defined in `SecretObjects`. The reconciler adds the consuming pods/replicaset as owner to the secrets it creates. This ties the lifetime of the secrets created by the CSI driver to the pods consuming. 

> Controller should check for existing owner references with controller: true before patching secrets. The controller should also set controller owner references on secrets it creates.

We don't set the controller as owner reference for the Kubernetes secret because the secret lifetime should be tied to the pod referencing the `SecretProviderClass`. The secrets will automatically be deleted when the last pod/replicaset using it gets deleted.

**Comment by terinjokes** [comment]
> The secrets will automatically be deleted when the last pod/replicaset using it gets deleted.

Noted. I understand the desire here, though I wish there was a better way of signaling the garbage collector.

I still believe this controller should respect controller owner references from other controllers, otherwise these two will just be fighting over the secret's data.

**Comment by aramase** [comment]
> I still believe this controller should respect controller owner references from other controllers, otherwise these two will just be fighting over the secret's data.

Is there another controller that's adding itself as owner ref to the Kubernetes secret created by the CSI driver? The reconciler gets the existing owner refs and appends the new ones to it. It doesn't delete any existing owner refs.

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/58c586d3bb3286115ef0ec2fd44b4e5419334b9a/controllers/secretproviderclasspodstatus_controller.go#L451

**Comment by terinjokes** [comment]
Most other controllers that touch secrets that someone might deploy into a Kubernetes cluster will set the controller owner reference (and look for it already being set) when creating secrets. The absence of respecting that flag here is what causes the problems.

**Comment by aramase** [comment]
@terinjokes That's interesting. So what is the reason for using the same secret name as the decrypted Secret? Is it to use 1 secret to have all the credentials?

Today, typically the secret gets created by the SecretProviderClass and the owner ref is set by it. But this would be an interesting scenario.

**Comment by terinjokes** [comment]
Right now there's a CRD, let's call it "EncryptedSecret", in it it defines a secretName. An existing operator running in Kubernetes decrypts this CRD and creates a secret (named with the value of secretName). This new secret sets the ownerReference field with `controller: true` on this newly created secret, to signal to other controllers that it is the owning controller.

We want to switch to Vault, and use secrets-store-csi-driver as part of the migration (as medium-to-long term we want to exclusively use CSI mount for secrets). To be transparent to already deployed pods, we want to create "SecretProviderClass" configured with "SecretObjects" with the same secret name.

Well behaved controllers would respect the existing controller ownerReference and not mutate the secret. This would allow us to deploy the SecretProviderClass resources before removing the EncryptedSecret resources, allowing us to have a smooth migration.

What actually happens is secrets-store-csi-drive does not respect the existing ownerReference and mutates the secret to match Vault. The existing controller sees this change, knows it's still the owner, and immediately sets it back. Eventually secrets-store-csi-driver reconciles and this back and forth repeats.
