### ISSUE TITLE
SecretProviderClass metrics

### ISSUE THREAD

**Issue by mitsutaka** [kubernetes-sigs/secrets-store-csi-driver#514]
**Describe the solution you'd like**
I want to add metrics of generic status about `SecretProviderClass` respectively like kube-state-metrics' [Secret metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/secret-metrics.md). It will be useful to summarize SecretProviderClass with labels.

**Anything else you would like to add:**
| Metric name| Metric type | Labels/tags |
| ---------- | ----------- | ----------- |
| kube_secretproviderclass_info | Gauge | `secretproviderclass`=&lt;spc-name&gt; <br> `namespace`=&lt;spc-namespace&gt; |
| kube_secretproviderclass_type | Gauge | `secretproviderclass`=&lt;spc-name&gt; <br> `namespace`=&lt;spc-namespace&gt; <br> `type`=&lt;syncing-secret-type&gt; <br> `provider`=&lt;provider-name&gt;|
| kube_secretproviderclass_labels | Gauge | `secretproviderclass`=&lt;spc-name&gt; <br> `namespace`=&lt;spc-namespace&gt; <br> `label_SPC_LABEL`=&lt;SPC_LABEL&gt; |
| kube_secretproviderclass_created  | Gauge | `secretproviderclass`=&lt;spc-name&gt; <br> `namespace`=&lt;spc-namespace&gt; |
| kube_secretproviderclass_metadata_resource_version  | Gauge | `secretproviderclass`=&lt;spc-name&gt; <br> `namespace`=&lt;spc-namespace&gt; |

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `v0.0.21`
- Kubernetes version: (use `kubectl version`):

**Comment by tam7t** [comment]
@mitsutaka are you interested in implementing this?

**Comment by mitsutaka** [comment]
@tam7t yeah I'm going to do unless any maintainer will work for it. Currently, the only place we can implement is the `DaemonSet` workload, and it's bound to `ClusterRole` that can reads `SecretProviderClass`, so I think I'll just add it to this to secrets-store-csi-driver.

**Comment by aramase** [comment]
@mitsutaka Thank you! I'll assign this issue to you.

/assign @mitsutaka

**Comment by mitsutaka** [comment]
Update:
Due to the upcoming release of otel v1.0.0, I will update the package. There are so many breaking changes. we should update now because there are still few metrics in secrets-store-csi-driver. I'm going to refactor the PR and address comments.
