### ISSUE TITLE
Aks cluster cannot pull the secrets using secrets store csi driver secretproviderclasses.secrets-store.csi.x-k8s.io is forbidden: User "system:serviceaccount:com-att:secrets-store-csi-driver"

### ISSUE THREAD

**Issue by mu5341** [kubernetes-sigs/secrets-store-csi-driver#523]
Hi:

We are implementing an AKS cluster to access the KeyVault using the secrets store YAML files.
We followed this document from Microsoft https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes
These are the steps that we follow:

1.) Deployed the YAML files directly
![image](https://user-images.githubusercontent.com/83474543/116748783-8a5e0100-a9c5-11eb-9950-e22008771e17.png)

csi-secrets-store-fxzpw                      3/3     Running   0          2d2h
csi-secrets-store-tjm7r                      3/3     Running   0          2d1h

com-att                   csi-secrets-store-provider-azure-j59ls                            1/1     Running             0          20h
com-att                   csi-secrets-store-provider-azure-qp6g5                            1/1     Running             0          20h
com-att                   csi-secrets-store-provider-azure-secrets-store-csi-driver-xh4b4   3/3     Running             0          20h
com-att                   csi-secrets-store-provider-azure-secrets-store-csi-driver-zn4nz   3/3     Running             0          20h

2.) Created SecretProviderClass
![image](https://user-images.githubusercontent.com/83474543/116751858-3f92b800-a9ca-11eb-9572-0425adc6f0a9.png)

3.) queried the information for AKS metadata
az aks show --name <cluster name>-aks--resource-group <resorucegroup> --subscription <SubscriptionID>
And got the following fields:
principalId
clientId
SubscriptionID
nodeResoursegroup

4.) queried Vault for metadata:
az keyvault secret list --vault-name <vaultname> --resource-group  <vault resoruce group> --subscription <SubscriptionId>
And got the following fields:
VAULT_RESOURCE_GROUP
tenantId

Other fields on the document:
NODE_RESOURCE_GROUP=nodeResoursegroup
SUBID=Azure SubscriptionID

az role assignment create --role "Managed Identity Operator" --assignee $clientId --scope /subscriptions/$SUBID/resourcegroups/$VAULT_RESOURCE_GROUP

az role assignment create --role "Managed Identity Operator" --assignee $clientId --scope /subscriptions/$SUBID/resourcegroups/$NODE_RESOURCE_GROUP

az role assignment create --role "Virtual Machine Contributor" --assignee $clientId --scope /subscriptions/$SUBID/resourcegroups/$NODE_RESOURCE_GROUP

3.) We run the following charts:
![image](https://user-images.githubusercontent.com/83474543/116750724-82539080-a9c8-11eb-8436-6f8f34f9c111.png)

4.) Created the Identity 
 az identity create -g $NODE_RESOURCE_GROUP -n testManagedIdentity

Output:
{
  "clientId": "Xd2",
  "clientSecretUrl": "https://control-eastus2.identity.azure.net/subscriptions/SUBID/resourcegroups/NODE_RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testManagedIdentity/credentials?tid=xxx&oid=xxx=xxxx",
  "id": "/subscriptions/SUBID/resourcegroups/NODE_RESOURCE_GROUP /providers/Microsoft.ManagedIdentity/userAssignedIdentities/testManagedIdentity",
  "location": "eastus2",
  "name": "testManagedIdentity",
  "principalId": "xxxxxx",
  "resourceGroup": "NODE_RESOURCE_GROUP",
  "tags": {},
  "tenantId": "X56",
  "type": "Microsoft.ManagedIdentity/userAssignedIdentities"
}

az keyvault set-policy -n KeyVaultName --secret-permissions get --spn Xd2
az keyvault set-policy -n KeyVaultName  --key-permissions get --spn Xd2
az keyvault set-policy -nKeyVaultName  --certificate-permissions get --spn Xd2

apiVersion: vi /v1
kind: AzureIdentity
metadata:
    name: testManagedIdentity                 # The name of your Azure identity
spec:
    type: 0                                 # Set type: 0 for managed identity
    resourceID: /subscriptions/SUBID/resourcegroups/NODE_RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testManagedIdentity
    clientID: "Xd2"   # The clientId of the User-assigned managed identity that you created earlier
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: "testManagedIdentity"      # The name of your Azure identity
    selector: azure-pod-identity-binding-selector

apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-store-inline
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector 
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-nprd-fplt01-kv  #The name for the class Secret Provided class

     And the deployment is not working

![image](https://user-images.githubusercontent.com/83474543/116752314-0870d680-a9cb-11eb-8504-9b3a7a526115.png)

We verified the User-assigned Managed Identity and exist and the Access policies for the User-assigned have both GET and LIST permissions.

We added to the KeyVault FW rules with the AKS virtual networks and still not able to work.

Any suggestions on how to troubleshoot this issue?

**Comment by nilekhc** [comment]
@mu5341 Could you provide following:
1. Kubernetes version
2. CSI Driver and provider version

**Comment by nilekhc** [comment]
Also you have installed driver twice.

>csi-secrets-store-fxzpw 3/3 Running 0 2d2h
csi-secrets-store-tjm7r 3/3 Running 0 2d1h

>com-att csi-secrets-store-provider-azure-j59ls 1/1 Running 0 20h
com-att csi-secrets-store-provider-azure-qp6g5 1/1 Running 0 20h
com-att csi-secrets-store-provider-azure-secrets-store-csi-driver-xh4b4 3/3 Running 0 20h
com-att csi-secrets-store-provider-azure-secrets-store-csi-driver-zn4nz 3/3 Running 0 20h

Could you uninstall and install driver either via helm or deploy yaml files?

**Comment by mu5341** [comment]
Hi:
I had to clean up the following K8S files:

![image](https://user-images.githubusercontent.com/83474543/116946569-14b19980-ac40-11eb-9846-bf12b41e48ca.png)

After that, I did the manual installation using helm:

helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

helm install pod-identity aad-pod-identity/aad-pod-identity
![image](https://user-images.githubusercontent.com/83474543/116946337-79202900-ac3f-11eb-970b-5c986dc0ed8d.png)


 Then CSI driver was able to pick up the keys from the key vault.

**Comment by aramase** [comment]
@mu5341 Is this issue resolved now? Could we close the issue?

**Comment by mu5341** [comment]
I think it will be good to know, how we can use the CSI driver when it is already installed in a non-default namespace. The Azure cloud requires to Ensure AKS Clusters Implement Kubernetes RBAC with Azure AD integration, but different automations don't deploy in the default namespace. Apperantly, only deploying into the default namespace we were able to make it work, but that broke the Security check.

Also, is there a way that we can inject the secrets values directly to the POD as env variables, instead mounting them? Any example on this?

**Comment by aramase** [comment]
> I think it will be good to know, how we can use the CSI driver when it is already installed in a non-default namespace. The Azure cloud requires to Ensure AKS Clusters Implement Kubernetes RBAC with Azure AD integration, but different automations don't deploy in the default namespace. Apperantly, only deploying into the default namespace we were able to make it work, but that broke the Security check.

@mu5341 The driver and provider can be installed in any namespace. The issue above is because the driver was installed twice (once with helm and then `kubectl deploy`) in multiple namespaces. 

> Also, is there a way that we can inject the secrets values directly to the POD as env variables, instead mounting them? Any example on this?

The mount is mandatory for syncing as Kubernetes secrets and using the Kubernetes secrets as env variables.

**Comment by mu5341** [comment]
Ok thanks you can close the ticket.
