### ISSUE TITLE
CSI Driver is not able to get serviceaccount token

### ISSUE THREAD

**Issue by mehmetsalgar** [kubernetes-sigs/secrets-store-csi-driver#542]
**What steps did you take and what happened:**
I am trying to use Hashi Corp Vault with CSI after I followed the instruction, I am getting the message the CSI driver can find service account token from Kubernetes API. My Helm Chart is deployed to Rancher and I found some posts that CSI Driver is not working on Rancher with default setttings but I can't find any confirmations about. Unfortunately I have no chance to change the settings of the Rancher as suggested in the Post. If you confirm this is a Rancher Problem I will stop using the CSI driver.

**What did you expect to happen:**

**Anything else you would like to add:**
You can see here name of the pod having problems
![pod_name_edited](https://user-images.githubusercontent.com/433232/118396269-12dbd300-b64f-11eb-82b4-70f66f3c3307.png)
and here you can see that Pod managed to mount the service account Token
![token_mount_edited](https://user-images.githubusercontent.com/433232/118396274-196a4a80-b64f-11eb-9dcf-f1b977120451.png)
but csi driver is not able to locate the token
![kubernetes_api_edited](https://user-images.githubusercontent.com/433232/118396280-2129ef00-b64f-11eb-91ce-cbe5befabee2.png)

**Which provider are you using:**
HashiCorp Vault

**Environment:**
Rancher 2.4.5
Kubernetes: v1.17.9

- Secrets Store CSI Driver version: (use the image tag): v0.0.21
- Kubernetes version: (use `kubectl version`): v1.17.9

**Comment by aramase** [comment]
Hey @mehmetsalgar, thanks for opening the issue. Please take a look at https://github.com/hashicorp/vault-csi-provider/issues/95 which is the similar issue and has the resolution.

cc @tomhjp

**Comment by aramase** [comment]
@mehmetsalgar Did you get a chance to look at the issue in the vault provider? Is the issue resolved now?

**Comment by mehmetsalgar** [comment]
Unforuntanetly our Rancher installation is not under our control, and I can bring system responsibles to set these flags for Rancher. So I can't verify this fix works or not.

**Comment by aramase** [comment]
@mehmetsalgar Thanks for the update! I'll close this issue now as it's specific to the vault provider. If you're still facing issues, please feel free to open an issue [here](https://github.com/hashicorp/vault-csi-provider/issues).

/close
