### ISSUE TITLE
integration tests for successful unmount

### ISSUE THREAD

**Issue by tam7t** [kubernetes-sigs/secrets-store-csi-driver#546]
**Describe the solution you'd like**
A test that ensures unmounts complete successfully on pod termination.

**Anything else you would like to add:**

#526 removed some code and integration tests passed. It was only through manual verification that it was discovered that deletion before unmount was actually required: #545

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by tam7t** [comment]
When I mess with the kubelet filesystem to induce a `NodeUnpublishVolume` error I get:

```
W0616 19:21:31.584690       1 mount_helper_common.go:129] Warning: "/var/lib/kubelet/pods/2610eccb-c4db-42da-be9b-56f8e472f0a6/volumes/kubernetes.io~csi/mysecret/mount" is not a mountpoint, deleting
E0616 19:21:31.584800       1 nodeserver.go:247] "failed to clean and unmount target path" err="remove /var/lib/kubelet/pods/2610eccb-c4db-42da-be9b-56f8e472f0a6/volumes/kubernetes.io~csi/mysecret/mount: directory not empty" targetPath="/var/lib/kubelet/pods/2610eccb-c4db-42da-be9b-56f8e472f0a6/volumes/kubernetes.io~csi/mysecret/mount"
E0616 19:21:31.584875       1 utils.go:79] GRPC error: rpc error: code = Internal desc = remove /var/lib/kubelet/pods/2610eccb-c4db-42da-be9b-56f8e472f0a6/volumes/kubernetes.io~csi/mysecret/mount: directory not empty
```

in the driver logs and the pod stuck in the `Terminating` state for multiple minutes.

From `kubectl describe`:

```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 16 Jun 2021 15:19:31 -0400
      Finished:     Wed, 16 Jun 2021 15:20:26 -0400
```

But I dont see any 'events' on the pod about failed unpublish:

```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m43s  default-scheduler  Successfully assigned default/mypod to gke-cluster-a-pool-cpu-b7bb9fe4-pzo4
  Normal  Pulled     5m41s  kubelet            Container image "gcr.io/google.com/cloudsdktool/cloud-sdk:slim" already present on machine
  Normal  Created    5m41s  kubelet            Created container mypod
  Normal  Started    5m41s  kubelet            Started container mypod
  Normal  Killing    4m46s  kubelet            Stopping container mypod
```

I think a test that deletes a pod with a mount and then does a:

```
kubectl wait --for=delete pod/mypod --timeout=60s
```

should reasonably catch failures on unmount

**Comment by aramase** [comment]
> in the driver logs and the pod stuck in the Terminating state for multiple minutes.

I don't think this is actually the case. I've seen the pods on linux nodes linger for longer sometimes even with successful unmount. However on windows the pods do get deleted pretty quickly. It might be hard to correlate the terminating time to an actual error without much info in the events. Although I understand generating an event for a deleting pod doesn't provide much as there is no potential user action to fix internal issues.
