### ISSUE TITLE
Feature Request: Regex based on Tag Based KV Objects Fetch

### ISSUE THREAD

**Issue by sudharsan89** [kubernetes-sigs/secrets-store-csi-driver#55]
This is a suggestion for a feature. Within a cluster, there would be different services deployed in different pods that might make use of the different secrets/keys/certs within a pod. It would be great if the resources can be fetched based on a regex or tags(in the case of azure).
For e.g. Pod A needs secret1, secret2 and Pod B needs Secret2, Secret3. 
Secret 1 has tag (Key: Pod, Value: Pod A)
Secret 2 has tag (Key: Pod, Value: Pod A ,Pod B)
Secret 3 has tag (Key: Pod, Value: PodB)

Once tagging these resources are done when creating each of these secrets, the pods as such just need something like 

  objects:  |
        array:                        # array of objects
          - |
            objectTagKey: (string/regex)
            objectTagValue: (string/regex)
            objectType: secret        # object types: secret, key or cert
            objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty

**Comment by aramase** [comment]
/close

This is a provider specific enhancement and is being tracked in provider repo.
