### ISSUE TITLE
Enable `--filtered-watch-secret` by default in `v0.1.0`

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#550]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/e2f85d3a3a8d3c87fd24170e213284aa70f61e07/deploy/secrets-store-csi-driver.yaml#L53

Reference docs on action to take: https://secrets-store-csi-driver.sigs.k8s.io/load-tests.html

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by tam7t** [comment]
This was set on https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/594
