### ISSUE TITLE
Migrate providers to include files in grpc responses

### ISSUE THREAD

**Issue by tam7t** [kubernetes-sigs/secrets-store-csi-driver#551]
Originally proposed in #460, the gRPC interface has been expanded to allow providers to [return a view of the filesystem in the RPC response](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/e2f85d3a3a8d3c87fd24170e213284aa70f61e07/provider/v1alpha1/service.proto#L64-L69), making the driver responsible for writing the files to the actual mount.

The interface was added in `v0.0.21` and `v0.0.22` will include #500 for atomic updates.

Providers should implement the new interface as optional (configurable through command line flag when deploying the provider) in preparation for it to be the default/required method for writing files in a future release.

**Comment by tam7t** [comment]
| provider | status |
|---|----|
| azure | [0.15.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/0.0.15) |
| vault | [0.3.0](https://github.com/hashicorp/vault-csi-provider/releases/tag/0.3.0) |
| gcp | [v0.4.0](https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/CHANGELOG.md#v040) |
| aws | https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/27 |

**Comment by aramase** [comment]
/remove-lifecycle stale

Pending release from aws provider with default behavior of sending files in grpc response

**Comment by aramase** [comment]
/remove-lifecycle stale

@tam7t should we keep this open until aws changes the default behavior?

cc @joebaro

**Comment by aramase** [comment]
cc @simonmarty
