### ISSUE TITLE
Feature Request: Include an optional file name

### ISSUE THREAD

**Issue by sudharsan89** [kubernetes-sigs/secrets-store-csi-driver#56]
This is a suggestion for a new feature. In addition to specifying the objectType and objectName, it would be good to include something like a outputFileName. There are times when a service needs different secrets for.e.g based on the region/environment although these are present in the same keyvault. If we support the outputFileName, the underlying service can still be agnostic of this.

For e.g Let us say there is a CognitiveServicesWestUs key and a CognitiveServicesEastUs key.
The definition for pod in westus would look like
objects: |
array: # array of objects
- |
objectName: CognitiveServicesWestUs
objectType: secret # object types: secret, key or cert
outputFileName: CognitiveServicesKey

The definition for pod in eastus would look like
objects: |
array: # array of objects
- |
objectName: CognitiveServicesEastUs
objectType: secret # object types: secret, key or cert
outputFileName: CognitiveServicesKey
objectVersion: "" # [OPTIONAL] object versions, default to latest if empty

It is very easy to use control structures in helm to specify the keys here in the yaml as opposed to the underlying service making the decision.

Also when you add new regions for e.g. it would not require changes in the underlying service.

**Comment by aramase** [comment]
This is currently being tracked in https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/24

/close
