### ISSUE TITLE
pods not creating after integrating csi

### ISSUE THREAD

**Issue by vpernankil** [kubernetes-sigs/secrets-store-csi-driver#572]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
This is the issue we are seeing while pod is starting 
Type Reason Age From Message
---- ------ ---- ---- -------
Warning FailedMount 25m (x224 over 13h) kubelet MountVolume.SetUp failed for volume 'secrets-store-inline' : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: nmi response failed with status code: 404, err: nil
Warning FailedMount 10m (x281 over 13h) kubelet Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-kcqmf]: timed out waiting for the condition
Warning FailedMount 4m4s (x85 over 13h) kubelet Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[default-token-kcqmf secrets-store-inline]: timed out waiting for the condition

**What did you expect to happen:**

pods should run 

**Anything else you would like to add:**
NA

**Which provider are you using:**

Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: 0.0.17
- Kubernetes version: (use `kubectl version`):  1.20.2  ( kubectl version : Client Version: version.Info{Major:"1", Minor:"20" )

**Comment by aramase** [comment]
@vpernankil Thank you for reporting the issue. This issue is specific to the Azure Provider for Secrets Store CSI Driver. Could you open an issue [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues). Please include the relevant logs in the issue.

The above error looks like the NMI component in aad-pod-identity is failing to obtain a token for the pod. Please check the MIC logs for error.

**Comment by aramase** [comment]
@vpernankil I'm closing this issue now because this is specific to the Azure Keyvault provider. Please feel free to open an issue [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) if you're still seeing any errors.

/close
