### ISSUE TITLE
Error with Mounting SecretproviderClass with AWS Provider

### ISSUE THREAD

**Issue by ephriamj** [kubernetes-sigs/secrets-store-csi-driver#580]
Hello, 

  I'm receiving an error when I launch a new deployment.  These are the steps I'm using.

1. Deploy SecretProviderClass:  kubectl apply -f test-secrets-array.yaml
2. Create a deploy using helm

When I go to deploy pods, I receive an error:

`"Warning  FailedMount  23s (x7 over 55s)  kubelet, ip-10-6-19-185.ec2.internal  MountVolume.SetUp failed for volume "secrets" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod test-service/deployment-test-data-services-8646cdc588-vbz2p, err: rpc error: code = Unknown desc = Failed to load SecretProviderClass: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go value of type []*provider.SecretDescriptor"`

Here's how my manifest is setup for SecretProviderClass:

```apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: eks-test-secrets
  namespace: test-services
spec:
  provider: aws
  parameters:
    objects: |
      array:
        - |
          objectName: "arn:aws:secretsmanager:us-east-1:174596742332:secret:test1-qlL3Np"
        - |
          objectName: "arn:aws:secretsmanager:us-east-1:174596742332:secret:testsecret-uDiDIO"
```

I also added the parameter:

--set grpcSupportedProviders=”aws”

Just wanted to see if anyone's having the same issue.  Thanks.

**Comment by aramase** [comment]
@ephriamj Thank you for reporting the issue.

This error seems to be specific for the aws provider. Could you open an issue [here](https://github.com/aws/secrets-store-csi-driver-provider-aws)?

cc @lasred

**Comment by ephriamj** [comment]
Thanks you @aramase.  Just created a new on for the AWS Provider.  Closing this one out now

**Comment by Ferat-Imrak** [comment]
Hello, @ephriamj I am having the same issue. Did you solve this? Let me know pls!!

**Comment by fcbavya** [comment]
Hi, I am facing same issue. Is this issue fixed? What is the fix?
