### ISSUE TITLE
Deprecate `--filtered-watch-secret` flag

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#597]
/kind cleanup

**Comment by sozercan** [comment]
Is there a deprecation process defined?

**Comment by aramase** [comment]
This has been the process so far:

1. Deprecate the flag in the code (Setting the flag no longer takes effect)
2. Remove the flag completely after n+2 releases

**Comment by 616b2f** [comment]
@aramase any insides about why it is depricated? I mean it was set to true in v0.1.0 via this PR #550 and was mentioned in the release notes of the last release? Can you please help me to understand.

**Comment by aramase** [comment]
> @aramase any insides about why it is depricated? I mean it was set to true in v0.1.0 via this PR #550 and was mentioned in the release notes of the last release? Can you please help me to understand.

The feature is enabled in `v0.1.0`. The flag will be deprecated as this is going to be default behavior and will not be configurable going forward.
