### ISSUE TITLE
Feature Request: Option to read a value from inside the secret for key/value secrets

### ISSUE THREAD

**Issue by lasred** [kubernetes-sigs/secrets-store-csi-driver#610]
**Describe the solution you'd like**
The aws provider has a feature request - https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/11 from a customer that would like to be able to select individual key/value pairs from a json secret.

I wanted to open the same ticket against the driver repository to gauge the community interest in a feature like this

It makes sense for this functionality to be implemented in the driver so that it can be reused for all providers 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by asonnleitner** [comment]
@lasred any update on that?
