### ISSUE TITLE
Azure Security Alert because of setting privileged mode true for secret store CSI Driver

### ISSUE THREAD

**Issue by albertsebastian1** [kubernetes-sigs/secrets-store-csi-driver#615]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Azure audit is reporting a security issue as running on privileged true. Requesting a feature to mitigate this. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
@albertsebastian1 The CSI driver needs to run in privileged mode to be able to do the mount. You can deploy the driver and provider in the `kube-system` namespace. There is a note in the installation doc about it

https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/

**Comment by aramase** [comment]
Closing this issue with reference to doc. If you have any further questions regarding the azure provider, please feel free to open an [issue](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues).

/close
