### ISSUE TITLE
"Failed to create Kubernetes secret error" when trying to sync AWS Secrets Manager to Kubernetes Secrets

### ISSUE THREAD

**Issue by ricardotasso** [kubernetes-sigs/secrets-store-csi-driver#618]
**What steps did you take and what happened:**
When doing the setup using Helm and syncing the Secrets from SPC to Kubernetes Secrets I am receiving the error message 
"secretproviderclasspodstatus_controller.go:325] "failed to create Kubernetes secret" err="secrets is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot create resource \"secrets\" in API group \"\" in the namespace \"default\"" spc="default/aws-secrets" pod="default/pod" secret="default/secret" spcps="default/pod-deployment-default-aws-secrets""

**What did you expect to happen:**
CSI Secrets Store Driver sync Secrets object to Kubernetes Secrets.

**Anything else you would like to add:**
To fix this I just added the permission below to the Cluster Role "[secretproviderclasses-role](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/role.yaml)"
```
- apiGroups:
  - ""
  resources:
  - secrets 
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
```
**Which provider are you using:**
AWS

**Environment:**

- Secrets Store CSI Driver version: v0.0.23
- Kubernetes version: 1.19

**Comment by nilekhc** [comment]
Hi @ricardotasso, Thanks for reporting this. sync secret is [disabled by default](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/221ef44211750661b2407e608ff707517d7a940a/charts/secrets-store-csi-driver/values.yaml#L186-L188). You can enable it by setting `syncSecret.enabled=true` while installing via helm.

cc @lasred

**Comment by tam7t** [comment]
It may help if on the install instructions [here](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#values) and call out rotation and secret sync features as explicitly
