### ISSUE TITLE
helm chart repo doesn't work

### ISSUE THREAD

**Issue by giuseppeiannelli** [kubernetes-sigs/secrets-store-csi-driver#621]
**What steps did you take and what happened:**
helm chart repo doesn't work

**What did you expect to happen:**
use repo as helm chart repo

**Anything else you would like to add:**
I tried to install helm chart from terraform using helm provider

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`): 1.21

**Comment by nilekhc** [comment]
@giuseppeiannelli Thanks for reporting this. Could you provide more detail on error you are getting?

**Comment by tam7t** [comment]
Specifically information on the version of helm and version of terraform that you are using would help as well. The provided PR seems to just update whitespace that we've used in the repo for a while so I'm suspicious that the issue is the yaml and not a parsing issue in one of the tools used.

**Comment by kitos9112** [comment]
I deployed the Helm chart version 0.0.23 last week without major complications using the Terraform Helm provider

These are the inputs of a custom Terraform module. Their names are pretty much mapping the actual provider plugin.
```hcl
  helm_release_name = secrets-store-csi-driver
  helm_repo_url     = "https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts"
  chart_namespace   = "kube-system"
  chart_name        = secrets-store-csi-driver
  chart_version     = "0.0.23"
```

**Comment by aramase** [comment]
@giuseppeiannelli Could you check the comment https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/621#issuecomment-878852103. The charts are working with terraform.

**Comment by gbarker** [comment]
Hi - may be related - I'm having trouble deploying the helm chart in aws-cdk 1.113.0 (build 61e1f65) / typescript- not sure what version of helm that's using.

my code:
```
function buildSecretsStoreCSIDriver(scope: cdk.Construct, cluster: eks.Cluster, appEnv: string) {

    return new eks.HelmChart(scope, 'csi-secrets-store', {
      cluster: cluster,
      chart: 'secrets-store-csi-driver/secrets-store-csi-driver',
      repository: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts',
      release: appEnv,
      namespace: 'kube-system',
      values: { 
          "grpcSupportedProviders": "aws", 
          // "enableSecretRotation": "true",
          // "rotationPollInterval": "3600s",
        }
    });
}
```

error reported by `cdk deploy`:
```
Error: chart "secrets-store-csi-driver/secrets-store-csi-driver" not found in https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-
csi-driver/master/charts repository
```

**Comment by giuseppeiannelli** [comment]
Changing repository from github.com to raw.githubusercontant.com the repository works.
