### ISSUE TITLE
`pull-secrets-store-csi-driver-e2e-gcp` failures due to expired credential

### ISSUE THREAD

**Issue by tam7t** [kubernetes-sigs/secrets-store-csi-driver#640]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/638

and

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/638/pull-secrets-store-csi-driver-e2e-gcp/1417196657778364416

```
E0719 19:06:30.971252       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod non-filtered-watch/secrets-store-inline-crd, err: rpc error: code = Internal desc = rpc error: code = Unauthenticated desc = transport: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/638/pull-secrets-store-csi-driver-e2e-gcp/1417196657778364416/artifacts/2021-07-19T190658/secrets-store.log

**What did you expect to happen:**

The pod should be able to auth to GCP Secret Manager API

**Comment by aramase** [comment]
Thank you for opening the issue @tam7t! Once you get a chance to update the creds in the prow cluster, we can retrigger the test in the PR to validate.
