### ISSUE TITLE
Secrets are not creates in kubernetes that are defined in the secretObjects section of the SecretProviderClass

### ISSUE THREAD

**Issue by chuckthompsonprofisee** [kubernetes-sigs/secrets-store-csi-driver#644]
**What steps did you take and what happened:**
The secrets are not being created in kubernetes  - This has been working for some time but on new deployments the secrets are not being created in k8.  the pod has the mount correctly mounted and I see the secrets in the mount, but they are not being created in kubernetes.  I have them defined in the SecretProviderClass in the secretObjects section.  my code has not changed and it used to work, and now it does not.  not sure when it stopped working but does not currently work nymore

**What did you expect to happen:**
The secret would be created in kubernets like it used to

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
Azure Key Vault

**Environment:**
AKS k8 version 1.19.11
- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by nilekhc** [comment]
hello @chuckthompsonprofisee , Thanks for reporting this. Could you provide which version of driver and provider you are using?

`syncSecret` is disabled by default in azure provider `v0.0.16`. You need to enable this to install required RBAC. Please refer to [release notes](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/0.0.16).

**Comment by chuckthompsonprofisee** [comment]
that worked!!  after adding the --set secrets-store-csi-driver.syncSecret.enabled=true to the helm install command for csi-secrets-store-provider-azure the secret are now there.  thanks!!

**Comment by nilekhc** [comment]
Closing this issue. Please open another one if you face any problem.

**Comment by nilekhc** [comment]
Closing this issue. Please open another if you face any problems.

/close
