### ISSUE TITLE
Secret object not updated after consecutive releases

### ISSUE THREAD

**Issue by bks-wujt** [kubernetes-sigs/secrets-store-csi-driver#674]
I use csi with GCP and mount it as secret object. Then utilize it as env within a pod.

**First release:**
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: gcp
  secretObjects:
    - secretName: secret-manager-synced-secrets
      type: Opaque
      data:
        - objectName: FB_VERIFICATION_TOKEN
          key: FB_VERIFICATION_TOKEN
  parameters:
    secrets: |
      - resourceName: "projects/project-id/secrets/FB_VERIFICATION_TOKEN/versions/latest"
        fileName: "FB_VERIFICATION_TOKEN"
```
```
$ kubectl describe secret secret-manager-synced-secrets
Name:         secret-manager-synced-secrets
Labels:       secrets-store.csi.k8s.io/managed=true
Annotations:  <none>

Type:  Opaque

Data
====
FB_VERIFICATION_TOKEN:      20 bytes

```

After first release everything is ok, but after second one - when I add more secrets (in the same manner as above) - the secret object is not being updated. I use helm and when I print release via `helm get all release-name` I can see that SecretProviderClass object is updated, but connected secret is not. Therefore new secrets are not mounted and pod is failing.

**Second release:**
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: gcp
  secretObjects:
    - secretName: secret-manager-synced-secrets
      type: Opaque
      data:
        - objectName: FB_VERIFICATION_TOKEN
          key: FB_VERIFICATION_TOKEN
        - objectName: FB_APP_SECRET
          key: FB_APP_SECRET
  parameters:
    secrets: |
      - resourceName: "projects/project-id/secrets/FB_VERIFICATION_TOKEN/versions/latest"
        fileName: "FB_VERIFICATION_TOKEN"
      - resourceName: "projects/project-id/secrets/FB_APP_SECRET/versions/latest"
        fileName: "FB_APP_SECRET"
```
```
$ kubectl describe secret secret-manager-synced-secrets
Name:         secret-manager-synced-secrets
Labels:       secrets-store.csi.k8s.io/managed=true
Annotations:  <none>

Type:  Opaque

Data
====
FB_VERIFICATION_TOKEN:      20 bytes

```

What I have tried:
1. Delete secret manually and also manually apply file SecretProviderClass - secret is not created at all.
2. Enabled [auto-rotation](https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html)

**Comment by aramase** [comment]
@bks-wujt Did you enable `syncSecret` as part of the helm install/upgade? With `v0.0.23` release, we disabled `syncSecret` by default in helm. If you're using the secrets-store-csi-driver to sync as Kubernetes secret, then you would need to explicitly set `syncSecret.enabled=true` when installing/upgrading the driver. 

Docs: https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#optional-values
Release notes:
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.23
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.1.0

**Comment by bks-wujt** [comment]
I did it explicitly:

```helm upgrade csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system --set syncSecret.enabled=true --set enableSecretRotation=true
```

**Comment by aramase** [comment]
Are you restarting the pod when updating the SecretProviderClass with new objects? The Kubernetes secret will only be updated by the rotation controller and default reconcile interval is 2m. So if you update the SecretProviderClass with new objects:
1. The mount will be updated after the rotation reconcile interval
2. The k8s secret will also be updated after the rotation reconcile interval
3. To get the env var for the new key, you can restart the pod

If you restart the pod along with the update to `SecretProviderClass`, the driver will not update the existing k8s secret if it already exists. The k8s secret is only done by the rotation controller. Ref: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#mounted-content-and-kubernetes-secret-not-updated

If you're following the 3 steps I shared above and are still seeing issues, please share the logs from driver and provider pod running on the same node as your app.

**Comment by bks-wujt** [comment]
Thanks for reply, @aramase. I did those steps and secret is still not being created.

```
k logs -n kube-system csi-secrets-store-secrets-store-csi-driver-dpgwq --all-containers
I0806 09:40:15.306388       1 main.go:113] Version: v2.2.0
I0806 09:40:15.307346       1 main.go:137] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0806 09:40:15.307387       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0806 09:40:19.907027       1 main.go:144] Calling CSI driver to discover driver name
I0806 09:40:19.907058       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0806 09:40:19.907065       1 connection.go:183] GRPC request: {}
I0806 09:40:20.109320       1 connection.go:185] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.23"}
I0806 09:40:20.109455       1 connection.go:186] GRPC error: <nil>
I0806 09:40:20.109469       1 main.go:154] CSI driver name: "secrets-store.csi.k8s.io"
I0806 09:40:20.109554       1 node_register.go:52] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0806 09:40:20.109818       1 node_register.go:61] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0806 09:40:20.110029       1 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0806 09:40:20.142550       1 main.go:80] Received GetInfo call: &InfoRequest{}
I0806 09:40:20.175812       1 main.go:90] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
I0806 09:40:15.510257       1 exporter.go:33] metrics backend: prometheus
I0806 09:40:16.661594       1 request.go:655] Throttling request took 1.049330964s, request: GET:https://10.31.112.1:443/apis/acme.cert-manager.io/v1alpha2?timeout=32s
I0806 09:40:19.716798       1 main.go:157] starting manager
I0806 09:40:19.718938       1 secrets-store.go:74] Driver: secrets-store.csi.k8s.io
I0806 09:40:19.718953       1 secrets-store.go:75] Version: v0.0.23, BuildTime: 2021-06-10-18:14
I0806 09:40:19.718957       1 secrets-store.go:76] Provider Volume Path: /etc/kubernetes/secrets-store-csi-providers
I0806 09:40:19.718962       1 secrets-store.go:77] GRPC supported providers will be dynamically created
I0806 09:40:19.718976       1 driver.go:80] "Enabling controller service capability" capability="CREATE_DELETE_VOLUME"
I0806 09:40:19.718989       1 driver.go:90] "Enabling volume access mode" mode="SINGLE_NODE_READER_ONLY"
I0806 09:40:19.718995       1 driver.go:90] "Enabling volume access mode" mode="MULTI_NODE_READER_ONLY"
I0806 09:40:19.719049       1 reconciler.go:125] starting rotation reconciler with poll interval: 1m0s
I0806 09:40:19.719366       1 server.go:111] Listening for connections on address: //csi/csi.sock
I0806 09:40:19.907105       1 main.go:149] calling CSI driver to discover driver name
I0806 09:40:20.109372       1 main.go:155] CSI driver name: "secrets-store.csi.k8s.io"
I0806 09:40:20.109410       1 main.go:183] ServeMux listening at "0.0.0.0:9808"
```

```
$ k logs -n kube-system csi-secrets-store-provider-gcp-dng2m
{"ts":1628242793121.634,"msg":"starting secrets-store-csi-driver-provider-gcp/v0.4.0","v":0}
{"ts":1628242793407.563,"msg":"health server listening","v":0,"addr":":8095"}
```

SecretProviderClass object is present in current release:
```
$ helm get all my-release

[...]

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: gcp
  secretObjects:
    - secretName: secret-manager-synced-secrets
      type: Opaque
      data:
      ...

```

```
$ k describe po core-ca-api-7dd596f4d7-kg9rz
...
Warning  FailedMount  33s (x11 over 6m45s)  kubelet            MountVolume.SetUp failed for volume "secrets" : secret "secret-manager-synced-secrets" not found
```

**Comment by aramase** [comment]
@bks-wujt I don't see any mount requests in the driver logs. Is this the log from the driver running on the same node as your app? Could you share the `SecretProviderClass` and `Pod` yaml?

**Comment by bks-wujt** [comment]
@aramase Yes, api pod and csi pods are in the same node, I have double checked that. What is more, when I first time did it, it went ok, secret was created and pod was using it correctly. Also, logs were showing some movement, eg gathering secret values during pod creation phase. 

But when updated deployment and added more secrets, things started working not as expected. When I tried different approaches, also I have deleted secret object. From then, even deployment was successful, the secret hasn't been created.

SecretProviderClass is [there](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/674#issue-959317702).

Pod:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    metadata:
   ...
    spec:
      serviceAccountName: secret-manager-accessor
   ...
        env:
        - name: FB_VERIFICATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-manager-synced-secrets
              key: FB_VERIFICATION_TOKEN
        - name: FB_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-manager-synced-secrets
              key: FB_APP_SECRET
   ...
```

**Comment by aramase** [comment]
@bks-wujt Could you post the entire deployment yaml with sensitive info redacted? I'm interested to see the `volumes` and `volumeMounts`.

**Comment by bks-wujt** [comment]
Hence I use secrets only as env's I do not mount this secret as volume to the pod.

**Comment by aramase** [comment]
Ah, the mount is mandatory. See https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html#sync-as-kubernetes-secret

```
The secrets will only sync once you start a pod mounting the secrets. Solely relying on the syncing with Kubernetes secrets feature thus does not work. When all the pods consuming the secret are deleted, the Kubernetes secret is also deleted.
```

The sync Kubernetes secret is an optional feature that's supported on top of the default mount. Without the mount, the CSI driver will never be invoked.

**Comment by bks-wujt** [comment]
Many thanks @aramase , I obviously missed that. Now it works like a charm.

I have question in addition - when using secrets as mounted files, the service account binded to workload identity is used in pod. In my case - hence I retrieve secret values from secret k8s object - I do not need it - then how the authentication is managed? Is CSI under the hood connects to SA workload identity associated to given cluster?

**Comment by tam7t** [comment]
The details of auth here are all specific to the GCP provider. There is some documentation here on how it works:

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/docs/authentication.md#pod-adc---pod-workload-identity-default

**Comment by aramase** [comment]
Closing this issue with @tam7t's comment on the internals.

Please feel free to reopen if you have any other questions.

/close
