### ISSUE TITLE
Job annotations

### ISSUE THREAD

**Issue by thomasmRavn** [kubernetes-sigs/secrets-store-csi-driver#675]
We use istio on our estate, which creates a sidecar to encrypt pod-pod communication.
This causes jobs to never complete because the side car never exits.
Istio can be turned off either by adding annotations to the pod or can be told to ignore pods with specific labels.
However we because both the daemonset and the job have the same labels, and you can't specify job annotations we can't tell istio to ignore the jobs keep-crds and upgrade-crds

**Describe the solution you'd like**
Happy to create a PR if you are ok with it, I think the easiest is to extend the work done https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/435 to include annotations for the jobs
That way you could pass the value linux.jobAnnotations to annotate the 2 jobs
can also split it out so there is a keepjob and updatejob if you wanted to have the option of different annotations for the 2 jobs.

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml#L25
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml#L49
All the labels in keep-crds-upgrade-hook are also in csi-driver and there are no annotations for the job either

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.1.0
- Kubernetes version: (use `kubectl version`): v1.20.5

**Comment by thomasmRavn** [comment]
Hi aramase, yes that is exactly what I mean. will try and get the pr to you sometime next week.

**Comment by thomasmRavn** [comment]
Hey @aramase sorry this took so long, you know how it is as soon as you pick something up 10 more things burst into flames.
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/692
Hope this is ok, please let me know if I've done anything wrong here. Tested it locally in kind and I can add annotations to the pods the job creates.

**Comment by nilekhc** [comment]
@thomasmRavn I think we should have test with these custom annotations. We can [add some test annotation](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/Makefile#L387-L401) to CRD hooks as part of our tests. Helm hooks relay on annotations as well, this way we can be assured that adding new annotations won't alter helm behaviour. WDYT?

cc @aramase @tam7t

**Comment by thomasmRavn** [comment]
^ ignore the "crds not called on 1st install" ran it locally and it looks like they are sorry

**Comment by nilekhc** [comment]
@thomasmRavn I looked at test runs. Annotation are being applied on `job.spec` and not on `job` itself. This will not conflict with helm behaviour. So we can revert this test changes or keep it. Either way should be ok.

Thanks!

**Comment by thomasmRavn** [comment]
@nilekhc yeah I needed the pod the job creates to have the annotations.
Thank you for your help
