### ISSUE TITLE
automatically integration test images before release promotion

### ISSUE THREAD

**Issue by tam7t** [kubernetes-sigs/secrets-store-csi-driver#688]
**Describe the solution you'd like**

During a release we:

1. bump the version number in a PR
1. merge the pr into the `release-X.X` branch
1. this kicks off the `secrets-store-csi-driver-push-image` prow job
1. that job kicks off a cloud build run to build the docker images and push them to staging `gcr.io/k8s-staging-csi-secrets-store`
1. we manually promote the staging images to the prod with a PR like https://github.com/kubernetes/k8s.io/pull/2530

Unfortunately the PR runs integration tests, but no integration tests are run post-commit on the release branch and none are run with the image built by cloud build.

Following  `secrets-store-csi-driver-push-image` the full integration test suite should be run against the image built by `secrets-store-csi-driver-push-image`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by aramase** [comment]
Adding to @tam7t write up, we run `release` tests when the deployment manifests and helm charts are updated as part of release. This tests the official published image. 

In addition to the release tests, running e2e tests against the staging image published will give us a signal if the image is good for promotion.

**Comment by nilekhc** [comment]
We have couple options for this:
1. We can have `postsubmit` job which will run on release branch. It will poll until staging image is available and then run e2e tests with mock provider.
2. We can have `github action`. Once staging images are available, we can manually trigger this action (possibly with input params such as registry name, image tag etc.) to run e2e tests with mock provider
