### ISSUE TITLE
test: `CSI inline volume test with pod portability - unmount succeeds` flaky

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#700]
This test is flaky mostly for the aws provider with the same error:

```console
not ok 11 CSI inline volume test with pod portability - unmount succeeds
# (from function `assert_success' in file test/bats/helpers.bash, line 8,
#  in test file test/bats/aws.bats, line 164)
#   `assert_success' failed with status 255
# pod/basic-test-mount condition met
# expected: 0
# actual: 255
# output: 
```

/kind failing-test
/cc @tam7t

**Comment by aramase** [comment]
ref: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/695/pull-secrets-store-csi-driver-e2e-aws/1428401286113398784/build-log.txt

**Comment by tam7t** [comment]
So AWS provider has 3 instances of this on the [testgrid](https://testgrid.k8s.io/sig-auth-secrets-store-csi-driver-postsubmit#secrets-store-csi-driver-e2e-aws-postsubmit) currently.

Each instance is the same error and when the artifacts are inspects it seems like the `basic-test-mount` is in fact deleted.

Leads me to believe that there is  a race between the `kubectl wait` and the `kubectl delete`.

**Comment by aramase** [comment]
Similar issue seen with the vault provider: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_secrets-store-csi-driver/708/pull-secrets-store-csi-driver-e2e-vault/1430239529716944896

**Comment by aramase** [comment]
We haven't seen this issue after #713 was merged. Closing this issue now.

/close
