### ISSUE TITLE
Permission denied when trying to create a pod

### ISSUE THREAD

**Issue by Uehara96** [kubernetes-sigs/secrets-store-csi-driver#728]
**What steps did you take and what happened:**
Installed `csi-secrets-store-csi-driver` and `vault-csi-provider` using helm and they are running in csi namespace.
Also did the kubernetes authentication.
Created the `SecretProviderClass` and the pod to read the secret from vault on namespace app. The pod keeps on `"ContainerCreating"` because it fails to create the volume and returns `"permission denied"`.
<img width="1049" alt="Screen Shot 2021-09-03 at 17 26 55" src="https://user-images.githubusercontent.com/42937807/132062296-c2ad97bb-7e90-48ba-ac6a-b346e949d64f.png">

Do I need to add more permissions to the service account?

**What did you expect to happen:**
Pod running and able to read the secret.

**Anything else you would like to add:**
Kubernetes cluster in AWS EKS.
Vault cluster hosted on AWS EC2.

**Which provider are you using:**
HashiCorp Vault

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): secrets-store-csi-driver-0.2.0
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-dispatcher", GitCommit:"a39a896b5018d0c800124a36757433c660fd0880", GitTreeState:"clean", BuildDate:"2021-01-28T22:06:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by aramase** [comment]
@Uehara96 Thanks for reporting the issue. Have you followed the documentation in the vault provider for setting up the required permissions: https://www.vaultproject.io/docs/platform/k8s/csi? 

Also, since this issue is specific to the vault provider, could you open an issue [here](https://github.com/hashicorp/vault-csi-provider/issues)?

**Comment by Uehara96** [comment]
Thanks for the reply @aramase. Yes, I followed this documentation for the authentication.
I'm going to close this issue here and create on the [vault-csi-provider](https://github.com/hashicorp/vault-csi-provider/issues/108).
