### ISSUE TITLE
E0909 failed to get pod Pod not found

### ISSUE THREAD

**Issue by jotasixto** [kubernetes-sigs/secrets-store-csi-driver#733]
**What steps did you take and what happened:**
A pod that has a secret associated with it is deleted, but the secret-store keeps trying to reconcile the secret in this pod even though it no longer exists. 

Log in secret-storage container of specific eks node:

```
secrets-store I0909 07:37:48.738989       1 secretproviderclasspodstatus_controller.go:227] "reconcile started" spcps="datadog/datadog-agent-5tlwk-datadog-datadog-ssm"
secrets-store E0909 07:37:48.739455       1 secretproviderclasspodstatus_controller.go:243] "failed to get pod" err="Pod \"datadog-agent-5tlwk\" not found" pod="datadog/datadog-agent-5tlwk"
secrets-store E0909 07:37:51.763441       1 reconciler.go:223] "failed to reconcile spc for pod" err="failed to get pod datadog/datadog-agent-5tlwk, err: Pod \"datadog-agent-5tlwk\" not found" spc="datadog-ssm" pod="datadog-agent-5tlwk" controller="rotation"
secrets-store E0909 07:37:53.095633       1 secretproviderclasspodstatus_controller.go:103] "failed to patch secret owner ref" err="failed to fetch pod during patching, err: Pod \"datadog-agent-5tlwk\" not found"
```

Indicate that despite this error registered in the logs, everything works as expected.

**What did you expect to happen:**
This should continue with the reconciliation without errors.

**Anything else you would like to add:**
I removed all components:
  - daemonset `csi-secrets-store-provider-aws`
  - csi driver `secrets-store.csi.k8s.io`
  - Secretproviderclass `datadog-ssm`

And after reinstalling everything again it keeps crashing with the same pod name and in the same eks node.

**Which provider are you using:**
AWS with this version image `public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-2021.08.13.20.34-linux-amd64`

**Environment:**

- Secrets Store CSI Driver version: 
        -  k8s.gcr.io/csi-secrets-store/driver:v0.2.0
        -  k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
- Kubernetes version: v1.21.2-eks-0389ca3

**Comment by aramase** [comment]
@jotasixto the CSI driver gets the pod to reconcile based on the `SecretProviderClassPodStatus` (SPCPS). When the SPCPS is created to signify the mapping between the pod and SecretProviderClass, the pod is added as an owner for the SPCPS. So when the pod gets deleted, the SPCPS will automatically be gc'ed by the kubernetes controllers. Looks like in your scenario the pod is gone but the SPCPS still exists?

Could you share the output for `kubectl get secretproviderclasspodstatus datadog-agent-5tlwk-datadog-datadog-ssm -n datadog -o yaml`?

> And after reinstalling everything again it keeps crashing with the same pod name and in the same eks node.

Is the `secrets-store` container restarting because of the error? If yes, what are the logs before the restart?

**Comment by jotasixto** [comment]
@aramase  Thank you very much for your quick reply!

I didn't know of the existence of the object `SecretProviderClassPodStatus` :sob:  . 

This is the output of the kubectl you told me:

```
❯ kubectl get secretproviderclasspodstatus -A
NAMESPACE   NAME                                                               AGE
datadog     datadog-agent-5tlwk-datadog-datadog-ssm                            10d
datadog     datadog-agent-cluster-agent-689d8b8956-p9rdd-datadog-datadog-ssm   17h
datadog     datadog-agent-gmdbb-datadog-datadog-ssm                            17h
datadog     datadog-agent-hk7sj-datadog-datadog-ssm                            17h

❯ kubectl get secretproviderclasspodstatus datadog-agent-5tlwk-datadog-datadog-ssm -n datadog -o yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClassPodStatus
metadata:
  creationTimestamp: "2021-08-30T13:21:37Z"
  generation: 1
  labels:
    internal.secrets-store.csi.k8s.io/node-name: ip-10-0-65-241.eu-west-1.compute.internal
  managedFields:
  - apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:internal.secrets-store.csi.k8s.io/node-name: {}
      f:status:
        .: {}
        f:mounted: {}
        f:objects: {}
        f:podName: {}
        f:secretProviderClassName: {}
        f:targetPath: {}
    manager: csi-secrets-store
    operation: Update
    time: "2021-08-30T13:21:37Z"
  name: datadog-agent-5tlwk-datadog-datadog-ssm
  namespace: datadog
  resourceVersion: "5428511"
  uid: 70a191f5-5b0c-4de1-ab8c-81f27044e339
status:
  mounted: true
  objects:
  - id: _secrets_k8s_cms_pro_datadog_apikey
    version: "1"
  podName: datadog-agent-5tlwk
  secretProviderClassName: datadog-ssm
  targetPath: /var/lib/kubelet/pods/7c0d6713-94e3-413e-a463-9ef2b2f2705f/volumes/kubernetes.io~csi/datadog-ssm/mount

```

I deleted the `datadog-agent-5tlwk-datadog-datadog-ssm` object and now the logs is clean of errors :tada: 


> Is the secrets-store container restarting because of the error? If yes, what are the logs before the restart?

The secret store container was not restarting, It just continuously wrote the four lines of error to the logs every few seconds.


Thank you very much for the help! Now everything is correct.
