### ISSUE TITLE
Manually trigger an update of mounted secrets from the secret store

### ISSUE THREAD

**Issue by lari002** [kubernetes-sigs/secrets-store-csi-driver#734]
**Describe the solution you'd like**
This is more a question, I apologize if it is inappropriate here.
Is it possible for the Secrets Store CSI Driver to somehow update mounted secrets without the reconciler and the pod restart?
In other words I would like to be able to update (manually for now) the secrets in the secrets store (AWS Secrets Manager)
and have them updated in the mounts but it would be perfectly fine if I had to trigger that propagation manually with the help of kubectl.

**Anything else you would like to add:**
According to the official K8s documentation, when a secret is updated, projected secrets in the volume mount will eventually be updated too (https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically).
The AWS provider warns about additional charges if the reconciler is used and I would like to avoid it and I don't have automatic rotation yet anyway.

**Environment:**

- Secrets Store CSI Driver version: none yet
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aramase** [comment]
@lari002 If you're not using the auto rotation feature, the only way to update the secrets in the mount is to restart the pod. When the new pod is created, it'll go through the volume mount again and the latest secrets will be fetched from the provider.

**Comment by lari002** [comment]
@aramase Thanks for the explanation.
