### ISSUE TITLE
How to use Azure App Service certificate in Nginx Ingress using CSI

### ISSUE THREAD

**Issue by jobinjosem1** [kubernetes-sigs/secrets-store-csi-driver#761]
**What steps did you take and what happened:**

We have a GoDaddy certificate procured using the Azure app service certificate. The certificate is exported into the KV as a secret. We would like to use this certificate in Nginx Ingress using CSI driver, for establishing TLS.
Looking at the SecretProviderClass in the samples, I understand there is a requirement to specify both tls.crt and tls.key but we only have the full pfx file in the KV. How can we use such a full pfx file in this scenario? Is it possible and if there are any samples available?
I understand it is possible to extract the key and crt from the pfx and can be used but that doesn't work well since the certificate autorenewals won't work. We have to extract and save new crt and key each time the certificate is renewed.

**Comment by aramase** [comment]
@jobinjosem1 As this is specific to the azure provider, could you instead open an issue here: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues?
