### ISSUE TITLE
Helm chart ARM64 support

### ISSUE THREAD

**Issue by jasonumiker** [kubernetes-sigs/secrets-store-csi-driver#794]
The Helm chart doesn't run on ARM64 Nodes such as AWS Graviton Instances. It looks like some work has been going on to support ARM64 but this has not yet made it into the Helm Chart.

**Comment by aramase** [comment]
Closing this issue with https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/794#issuecomment-951142135. The `driver` and `driver-crds` image are available for arm64. 

/close
