### ISSUE TITLE
Add feature-gate in aks-engine and AKS

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/secrets-store-csi-driver#8]

**Comment by aramase** [comment]
@andrebriggs Currently, there is no way to enable `--feature-gates` in aks, but this feature gate is enabled by default on 1.16+ clusters.

**Comment by aramase** [comment]
The [csi-secrets-store](https://github.com/Azure/aks-engine/tree/master/examples/addons/csi-secrets-store) addon has been added as default for 1.16+ in aks-engine clusters. Currently there is no way to add feature gates in AKS cluster, so the recommendation is to try out 1.16+ clusters in AKS while using `secrets-store-csi-driver`.

/close
