### ISSUE TITLE
Helm chart url leads to 404

### ISSUE THREAD

**Issue by Tahvok** [kubernetes-sigs/secrets-store-csi-driver#812]
The helm chart specified in the installation docs leads to 404:
https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts

As a workaround I had to install directly from git for now:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver

![Screenshot_20211122_093821](https://user-images.githubusercontent.com/6513056/142908980-71c6b510-0ffa-46e2-b26e-9bd101699ba9.png)

**Comment by nilekhc** [comment]
Hi @Tahvok, Thanks for reporting issue. I quickly tried adding helm repo and it worked fine for me.

![image](https://user-images.githubusercontent.com/1626598/142910457-a5d1896b-f68a-4c1d-91ed-0fa483f9c152.png)

**Comment by Tahvok** [comment]
You are right, it is working now. I probably had some issue. Closing.
