### ISSUE TITLE
metadata for synced secrets

### ISSUE THREAD

**Issue by cjyar** [kubernetes-sigs/secrets-store-csi-driver#819]
**Describe the solution you'd like**
For Secrets that are synced from the secrets provider, it would be nice to be able to control the metadata.

For example, ArgoCD uses Secrets that need particular labels. Other software may require annotations.

**Anything else you would like to add:**
I think just the ability to add k/v maps for labels and annotations would cover many use cases.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.0.0
- Kubernetes version: (use `kubectl version`): 1.21.5

**Comment by cjyar** [comment]
This was already done by #273 and #612. Sorry for the trouble.

**Comment by aramase** [comment]
Thank you for following up. We'll also get these configurations added to our documentation.
