### ISSUE TITLE
[Bug] providersDir should not default to `/etc/kubernetes` as primarily contains .sock files better held in `/var/run` or `/tmp/`

### ISSUE THREAD

**Issue by paulczar** [kubernetes-sigs/secrets-store-csi-driver#823]
When deployed the Secrets Store CSI Driver creates a socket in [/etc/kubernetes/secrets-store-csi-providers](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/manifest_staging/charts/secrets-store-csi-driver/values.yaml#L71), the `/etc/` path is really meant for [configuration files](https://www.linux.com/training-tutorials/linux-directory-structure-explainedetc-folder/), not unix sockets.  The more standard place to put socket files is `/var/run/` or somewhere in `/tmp`  If you explore a debian, redhat, or ubuntu box you'll find most sockets are in one of the two.

This can be a problem for Operating System and Security Controls that are protective of a systems /etc contents.

While this can be overridden in the helm chart by setting `linux.providersDir` the default is re-used in various providers, not all have a method to override it without manually editing the resources.

I would recommend modifying the default and cutting a major release to signify a breaking change to downstream projects.

**Comment by aramase** [comment]
Thanks for the feedback! I'll add this to our community call for discussion.
