### ISSUE TITLE
Chart bundle for v1.0.0 was not generated and added to the index file

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes-sigs/secrets-store-csi-driver#838]
Looks like the chart was updated for v1.0.0 but a bundle was not generated and the index was not updated to serve it.
https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts

**Comment by aramase** [comment]
@mitchellmaler Where are you checking for the bundle? It's available here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/gh-pages/charts/secrets-store-csi-driver-1.0.0.tgz and the index has it: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/gh-pages/charts/index.yaml#L4-L20

**Comment by aramase** [comment]
We moved to using `gh-pages` in `v0.0.3` release. The doc has the updated helm repo url:
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver#installing-the-chart - https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#installation
- https://secrets-store-csi-driver.sigs.k8s.io/getting-started/upgrades.html#pre-v030

**Comment by mitchellmaler** [comment]
Ah yea that would be the reason. Updating to the new branch fixes the issue.
I was looking under main and did not see the new version there.
