### ISSUE TITLE
Need a version of this image which can run as non-root user

### ISSUE THREAD

**Issue by ashok-e-singh** [kubernetes-sigs/secrets-store-csi-driver#842]
**Describe the solution you'd like**
We need this container to run as non-root user.

**Anything else you would like to add:**
Since its widely published that containers should run as non-root users, can we have a version of this which can run as non-root?
We have tried to add the user in the dockerbuild file using the USER command, but this wouldn't let the container run.

**Comment by nilekhc** [comment]
Hi @ashok-e-singh, Thanks for opening issue.

The driver pods need to run as root to mount the volume as tmpfs in the pod. It's installed as a DaemonSet with the ability to mount kubelet hostPath volumes and view pod service account tokens. It should be treated as privileged and regular cluster users should not have permissions to deploy or modify the driver. This is also the reason we recommend installing driver in kube-system namespace.

**Comment by ashok-e-singh** [comment]
Thanks for the response @nilekhc Much appreciated. Are u able to tell what are the security risks of this plugin running as a root user? We may have to come up with ways to circumvent it.

**Comment by nilekhc** [comment]
We have not came across any as of now. We also patch our images for CVEs. There is similar discussion going on in https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/432
