### ISSUE TITLE
Document all the flags supported by the driver

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#855]
/kind documentation

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/40a680657ca5f44c2893eb2098fd94b97b868c2a/cmd/secrets-store-csi-driver/main.go#L54-L69

- This will make it easier for announce flag deprecations
- Gives a better understanding of what the flag is and when to use it

**Comment by umeshkumhar** [comment]
@aramase hey I can take this issue.

Any extra details you want to share around this.?

Thanks

**Comment by nilekhc** [comment]
@umeshkumhar Thanks for your interest. We could add this under https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/docs/book/src/topics. 
A table like [helm chart values](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver) with defaults etc. would be a good start.

@aramase @tam7t Any additional thoughts?

**Comment by aramase** [comment]
Hello Umesh 👋🏻  

A section under topics is a good start as Nilekh suggested. You can use the flags defined in `main.go` for reference to document the configurable behavior.
