### ISSUE TITLE
Add a Prometheus Servicemonitor to Helm Chart

### ISSUE THREAD

**Issue by midnightconman** [kubernetes-sigs/secrets-store-csi-driver#865]
**Describe the solution you'd like**
I would like a servicemonitor object added to the helm chart, so helm users can easily enable metrics collection with the prometheus-operator and prometheus. Many servicemonitor object examples exist, links can be provided if needed.

**Anything else you would like to add:**
This might require changing the listening address for the metrics handler, not sure if that is required yet.

**Comment by nilekhc** [comment]
@midnightconman Would you like to open a PR to implement this?

**Comment by aramase** [comment]
Thank you for opening the issue!

We discussed this in the community call and the consensus is to not include additional yamls that aren't core for this project. If added, the config in helm chart would need to be tested and maintained up-to date with changes in service monitor which is out of the scope for the maintainers. I'm going to close this issue now but please feel free to open a new one if there any questions or you would like to see a new feature.

/close
