### ISSUE TITLE
Adds helm releases to repo or update docs for installation 

### ISSUE THREAD

**Issue by Driesvanherpe** [kubernetes-sigs/secrets-store-csi-driver#866]
**What steps did you take and what happened:**
We've been pulling the chart from te official helm chart repo as stated  in the docs, but the relaese only go to v0.2.0

**What did you expect to happen:**
Create tar.gz files in the `charts` directory

**Comment by aramase** [comment]
@Driesvanherpe The chart repo has been moved to `https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts`. This was done 6 months back and a note was added in the install docs and upgrade docs: https://secrets-store-csi-driver.sigs.k8s.io/getting-started/upgrades.html#pre-v030. That is the official helm chart repo and we'll be removing the old charts that were being served at `https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts` as part of [PR](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/850).

**Comment by Driesvanherpe** [comment]
Whoops, my apologies
