### ISSUE TITLE
failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/index.yaml : 404 Not Found

### ISSUE THREAD

**Issue by jkstenzel95** [kubernetes-sigs/secrets-store-csi-driver#890]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Followed the steps listed at [this url](https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html), which previously worked, and the command `helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts` results in the message `Error: looks like "https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/index.yaml : 404 Not Found`

**What did you expect to happen:**
The repository for the csi secrets driver to be added so I can proceed with getting my AWS secrets mounted to my EKS cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This previously worked for me. Did something change or is something broken? This has been happening since 3/3/22.

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
AWS

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

**Comment by nilekhc** [comment]
Hi @jkstenzel95 Our charts have been moved. Could you follow the steps from here: 
https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html#deployment-using-helm

**Comment by aramase** [comment]
I've opened a PR to update the docs in the aws provider: https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/73. 

For latest driver installation steps, please refer to the doc Nilekh posted.

/close
