### ISSUE TITLE
Informational messages are logged as errors

### ISSUE THREAD

**Issue by fubar** [kubernetes-sigs/secrets-store-csi-driver#909]
Our logs show the below messages logged frequently and at error level:

```
I0322 06:01:21.315168       1 secretproviderclasspodstatus_controller.go:222] "reconcile started" spcps="[...]"
I0322 06:01:21.315582       1 secretproviderclasspodstatus_controller.go:366] "reconcile complete" spc="[...]" pod="[...]" spcps="[...]"
```

These are informational messages that should not be treated like errors.

**Anything else you would like to add:**

- Standard integration with the AWS provider
- Standard Datadog agent logging setup

**Which provider are you using:**

AWS

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.1.1
- Kubernetes version: (use `kubectl version`): 1.21

**Comment by aramase** [comment]
By default, all the logs are written to stderr: https://github.com/kubernetes/klog/blob/main/klog.go#L38. 

The above logs should be generated once every 5m when the reconcile happens but I think we can bump the log verbosity to `V(5)` so it doesn't get logged by default.

**Comment by fubar** [comment]
> By default, all log statements write to standard error

That's a gross abuse of the log level system. Or rather, it's ignoring it entirely.

If the maintainers of klog are unwilling to fix this, it would be useful if the CSI driver exposed logging options to be passed to klog that change its behaviour, such as the `logtostderr` option that I see in that file. At the moment, the only logging related option I see is `logFormatJSON` https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/cmd/secrets-store-csi-driver/main.go#L55-L77

**Comment by aramase** [comment]
All the flags supported by klog should be configurable with the driver: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/3d93b4a03a68fd0de22fc09711734db0d2f51f70/cmd/secrets-store-csi-driver/main.go#L86. Have you tried setting any of the flags supported by klog on the driver?

> At the moment, the only logging related option I see is logFormatJSON

klog doesn't have a log format json flag, so we explicitly added that for the driver.

**Comment by aramase** [comment]
Closing with https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/909#issuecomment-1078726821

/close
