### ISSUE TITLE
CSI driver images running as non root user

### ISSUE THREAD

**Issue by teenarodriques** [kubernetes-sigs/secrets-store-csi-driver#941]
We are currently using the CSI driver images for Secret Manager in GCP. All the images used are running as root. Is it possible to have them running as non-root? 

The list of images being used are: 
k8s.gcr.io/sig-storage/csi-node-driver-registrar
k8s.gcr.io/csi-secrets-store/driver
k8s.gcr.io/sig-storage/livenessprobe
k8s.gcr.io/csi-secrets-store/driver-crds
us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin

These images are unable to pass Aquasec scans. Is there a way to mitigate this please?

**Comment by aramase** [comment]
See https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/159#issuecomment-1017748799 for more details

**Comment by aramase** [comment]
We have added a new security section in the docs, that mention why the driver and providers needs run as root: https://secrets-store-csi-driver.sigs.k8s.io/concepts.html#security. 

Closing this now. Please feel free to reopen if you have any questions.

/close
