### ISSUE TITLE
Synced Secrets don't refresh when changed in AWS Secrets Manager

### ISSUE THREAD

**Issue by absmith82** [kubernetes-sigs/secrets-store-csi-driver#981]
Not sure if this is an issue for this driver, or for the AWS provider so let me know if I need to close this issue for one in AWS.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created a SPC and was able to sync AWS secrets to K8s secrets.

Changed a secret in AWS Secrets Manager.

Restarted deployment.

Secret kept the old value rather than the new value.

Deleted K8s generated secret
restarted deployment

Secret synced with new value

**What did you expect to happen:**

Create a SPC and sync AWS secrets to K8s secrets.

Changed a secret in AWS Secrets Manager.

Restarted deployment.

K8s Secret to sync with the new value in AWS secrets

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
AWS

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.1.2
- Kubernetes version: (use `kubectl version`):  v1.22.9

**Comment by aramase** [comment]
@absmith82 Thanks for opening the issue.

This behavior is documented as a known limitation: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#how-to-fetch-the-latest-content-with-release-v0014-and-earlier-or-without-auto-rotation-feature-enabled. If you're manually deleting the deployment to get the latest secrets, you'll need to delete the k8s secret too with the deployment.

The secrets store csi driver does support auto-rotation that'll fetch the latest secrets periodically and update it in the mount and the k8s secret: https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html

**Comment by absmith82** [comment]
Thanks, I misunderstood what this feature did.  I thought it would enable auto-rotation at the provider level and would change the secrets automatically. Not just sync the changes.

Do you know when this feature will be out of Alpha, documentation says "Feature State: Secrets Store CSI Driver v0.0.15 [alpha]"

I would really like to use the feature but need to know that it is stable first.

**Comment by aramase** [comment]
> Do you know when this feature will be out of Alpha, documentation says "Feature State: Secrets Store CSI Driver v0.0.15 [alpha]"

The feature is well tested, been available for more than a year now and considered stable for production use. It's marked alpha as we're planning to move to kubernetes CSI driver [requires republish](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/585) for rotation instead of implementing it in the driver here.

**Comment by absmith82** [comment]
Thank you!!
