### ISSUE TITLE
csi driver pod in crashloop state on one new created AKS node

### ISSUE THREAD

**Issue by yeqing1206** [kubernetes-sigs/secrets-store-csi-driver#986]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created a new AKS node, then pod secrets-store-csi-driver-bjk7g got into crashloop state on this new created pod

logs showed errors:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x140aa05]
goroutine 28 [running]:
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping.func1()
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client/apiutil/dynamicrestmapper.go:255 +0x45
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload.func1(0x28, 0x38)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client/apiutil/dynamicrestmapper.go:155 +0x91
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload(0xc0004b1d10, {0x1c9bfe0, 0xc000610440}, 0xc0003510a0)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client/apiutil/dynamicrestmapper.go:156 +0x9c
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping(0xc0004b1d10, {{0x1a878ca, 0x166ca01}, {0x16a9010, 0x464591}}, {0xc0002f8c20, 0x1, 0x1})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client/apiutil/dynamicrestmapper.go:253 +0x168
sigs.k8s.io/controller-runtime/pkg/cache/internal.createStructuredListWatch({{0x1a878ca, 0x1a}, {0x1a6ab6e, 0x2}, {0x16a9010, 0x1c}}, 0xc0001e6380)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/cache/internal/informers_map.go:259 +0x14d
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).addInformerToMap(0xc0001e6380, {{0x1a878ca, 0x1a}, {0x1a6ab6e, 0x2}, {0x16a9010, 0x1c}}, {0x1cbdb40, 0x0})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/cache/internal/informers_map.go:223 +0x195
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get(0x2, {0x1ccf830, 0xc000141cc0}, {{0x1a878ca, 0x1a}, {0x1a6ab6e, 0x2}, {0x16a9010, 0x1c}}, {0x1cbdb40, ...})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/cache/internal/informers_map.go:195 +0xf6
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Get(0xc00068e000, {0x1ccf830, 0xc000141cc0}, {{0x1a878ca, 0x1a}, {0x1a6ab6e, 0x2}, {0x16a9010, 0x1c}}, {0x1cbdb40, ...})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/cache/internal/deleg_map.go:105 +0x279
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).List(0xc00011b698, {0x1ccf830, 0xc000141cc0}, {0x1d04210, 0xc00068e000}, {0xc0002f8ad0, 0x1, 0x1})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/cache/informer_cache.go:78 +0xe5
sigs.k8s.io/secrets-store-csi-driver/controllers.(*SecretProviderClassPodStatusReconciler).Patcher(0xc0003de300, {0x1ccf830, 0xc000141cc0})
    /go/src/sigs.k8s.io/secrets-store-csi-driver/controllers/secretproviderclasspodstatus_controller.go:112 +0x32a
sigs.k8s.io/secrets-store-csi-driver/controllers.(*SecretProviderClassPodStatusReconciler).RunPatcher(0x0, {0x1ccf830, 0xc000141cc0})
    /go/src/sigs.k8s.io/secrets-store-csi-driver/controllers/secretproviderclasspodstatus_controller.go:96 +0x11f
main.main.func4()
    /go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:189 +0x25
created by main.main
    /go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:188 +0xe95

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**
AKS 1.21.9

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
 AKS 1.21.9

**Comment by aramase** [comment]
@yeqing1206 That error indicates, the driver is unable to communicate with the `kube-apisever`. If you're using the AKS add-on, I would recommend opening an issue [here](https://github.com/Azure/AKS). If not using the managed add-on, check connectivity to the kube-apiserver from the node and also try to deploy the driver in `kube-system` namespace.
