### ISSUE TITLE
Question: Why do we have keep-crds-upgrade-hook.yaml file ?

### ISSUE THREAD

**Issue by sambhavdtu** [kubernetes-sigs/secrets-store-csi-driver#992]
My understanding is that helm never delete CRD resources. Why was there a need for adding helm.sh/resource-policy keep on the CRDs.
https://github.com/helm/community/pull/138/files

**Comment by nilekhc** [comment]
Hey @sambhavdtu Thanks for opening issue. This was mainly to move from helm 2 to helm 3. Helm 2 manages CRD lifecycle and deletes them after helm uninstall. keep-crds.yaml is to prevent that.

**Comment by nilekhc** [comment]
> Hi @nilekhc , Thanks Got it. I want to upgrade to the new CRD schema which has v1 version as storage in etcd. Since, helm3 only installs CRDs once at the time of chart install. Is it safe to use crds-upgrade-hook for that ?

The driver chart already has crd hook for this very purpose. So if you try to install or upgrade, hooks will make sure latest CRDs from `crd` directory gets applied.

**Comment by sambhavdtu** [comment]
Thanks @nilekhc for confirming that. Just want to point it out that in future when we fully migrate from v1alpha1 to v1, we would need to think for some other approach for CRD upgradation as it is not possible to remove a version from CRD definition once it is registered through kubectl . 
https://kubernetesquestions.com/questions/59452368
